
CREATE TABLE TB_ITEM (
    ITEM_ID VARCHAR(50) PRIMARY KEY,
    ITEM_NAME VARCHAR(100) NOT NULL,
    ITEM_TYPE VARCHAR(20),
    UNIT VARCHAR(10),
    DESCRIPTION TEXT,
    CREATED_BY VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE TB_PROCESS (
    PROCESS_ID VARCHAR(50) PRIMARY KEY,
    PROCESS_NAME VARCHAR(100),
    DESCRIPTION TEXT,
    CREATED_BY VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE TB_WORKCENTER (
    WORKCENTER_ID VARCHAR(50) PRIMARY KEY,
    WORKCENTER_NAME VARCHAR(100),
    LOCATION VARCHAR(100),
    CREATED_BY VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE TB_SUPPLIER (
    SUPPLIER_ID VARCHAR(50) PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(100),
    CONTACT_INFO TEXT,
    CREATED_BY VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE TB_USER (
    USER_ID VARCHAR(50) PRIMARY KEY,
    USER_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(255),
    ROLE_ID VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE TB_ROLE (
    ROLE_ID VARCHAR(50) PRIMARY KEY,
    ROLE_NAME VARCHAR(50),
    DESCRIPTION TEXT
);


CREATE TABLE TB_USER_ROLE (
    USER_ID VARCHAR(50),
    ROLE_ID VARCHAR(50),
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE(ROLE_ID)
);


CREATE TABLE TB_CODE_GROUP (
    CODE_GROUP_ID VARCHAR(50) PRIMARY KEY,
    GROUP_NAME VARCHAR(100)
);


CREATE TABLE TB_CODE (
    CODE_ID VARCHAR(50) PRIMARY KEY,
    CODE_GROUP_ID VARCHAR(50),
    CODE_NAME VARCHAR(100),
    FOREIGN KEY (CODE_GROUP_ID) REFERENCES TB_CODE_GROUP(CODE_GROUP_ID)
);
