
CREATE TABLE TB_PRODUCTION_PLAN (
    PLAN_ID VARCHAR(50) PRIMARY KEY,
    ITEM_ID VARCHAR(50),
    PLAN_DATE DATE,
    QUANTITY INT,
    STATUS VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM(ITEM_ID)
);


CREATE TABLE TB_WORK_ORDER (
    WORK_ORDER_ID VARCHAR(50) PRIMARY KEY,
    PLAN_ID VARCHAR(50),
    PROCESS_ID VARCHAR(50),
    WORKCENTER_ID VARCHAR(50),
    QUANTITY INT,
    START_DATE DATETIME,
    END_DATE DATETIME,
    STATUS VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PLAN_ID) REFERENCES TB_PRODUCTION_PLAN(PLAN_ID),
    FOREIGN KEY (PROCESS_ID) REFERENCES TB_PROCESS(PROCESS_ID),
    FOREIGN KEY (WORKCENTER_ID) REFERENCES TB_WORKCENTER(WORKCENTER_ID)
);


CREATE TABLE TB_OPERATION_LOG (
    LOG_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    WORK_ORDER_ID VARCHAR(50),
    USER_ID VARCHAR(50),
    START_TIME DATETIME,
    END_TIME DATETIME,
    RESULT_QUANTITY INT,
    DEFECT_QUANTITY INT,
    NOTE TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (WORK_ORDER_ID) REFERENCES TB_WORK_ORDER(WORK_ORDER_ID),
    FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID)
);


CREATE TABLE TB_PROCESS_ROUTE (
    ROUTE_ID VARCHAR(50) PRIMARY KEY,
    ITEM_ID VARCHAR(50),
    PROCESS_SEQ INT,
    PROCESS_ID VARCHAR(50),
    WORKCENTER_ID VARCHAR(50),
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM(ITEM_ID),
    FOREIGN KEY (PROCESS_ID) REFERENCES TB_PROCESS(PROCESS_ID),
    FOREIGN KEY (WORKCENTER_ID) REFERENCES TB_WORKCENTER(WORKCENTER_ID)
);


CREATE TABLE TB_EQUIPMENT_CHECK (
    CHECK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EQUIPMENT_ID VARCHAR(50),
    CHECK_DATE DATE,
    CHECK_RESULT VARCHAR(20),
    NOTE TEXT,
    CHECKED_BY VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EQUIPMENT_ID) REFERENCES TB_EQUIPMENT(EQUIPMENT_ID)
);


CREATE TABLE TB_EQUIPMENT_MAINTENANCE_LOG (
    MAINTENANCE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EQUIPMENT_ID VARCHAR(50),
    MAINTENANCE_DATE DATETIME,
    TYPE VARCHAR(50),
    NOTE TEXT,
    MAINTAINED_BY VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EQUIPMENT_ID) REFERENCES TB_EQUIPMENT(EQUIPMENT_ID)
);


CREATE TABLE TB_EQUIPMENT_STATUS (
    EQUIPMENT_ID VARCHAR(50) PRIMARY KEY,
    STATUS VARCHAR(20),
    LAST_CHECKED DATETIME,
    FOREIGN KEY (EQUIPMENT_ID) REFERENCES TB_EQUIPMENT(EQUIPMENT_ID)
);


CREATE TABLE TB_EQUIPMENT_SENSOR_LOG (
    LOG_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EQUIPMENT_ID VARCHAR(50),
    SENSOR_TYPE VARCHAR(50),
    VALUE DECIMAL(10, 2),
    LOGGED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EQUIPMENT_ID) REFERENCES TB_EQUIPMENT(EQUIPMENT_ID)
);
