CREATE TABLE TB_WAREHOUSE (
    WAREHOUSE_ID VARCHAR(50) PRIMARY KEY COMMENT '창고 ID',
    WAREHOUSE_NAME VARCHAR(100) NOT NULL COMMENT '창고명',
    LOCATION VARCHAR(100) COMMENT '위치',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE TB_MATERIAL (
    MATERIAL_ID VARCHAR(50) PRIMARY KEY COMMENT '자재 ID',
    MATERIAL_NAME VARCHAR(100) NOT NULL COMMENT '자재명',
    UNIT VARCHAR(20) COMMENT '단위 (EA, kg 등)',
    SUPPLIER_ID VARCHAR(50) COMMENT '공급처 ID',
    FOREIGN KEY (SUPPLIER_ID) REFERENCES TB_SUPPLIER(SUPPLIER_ID)
);
CREATE TABLE TB_STOCK (
    MATERIAL_ID VARCHAR(50) NOT NULL COMMENT '자재 ID',
    WAREHOUSE_ID VARCHAR(50) NOT NULL COMMENT '창고 ID',
    QUANTITY INT DEFAULT 0 COMMENT '재고 수량',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (MATERIAL_ID, WAREHOUSE_ID),
    FOREIGN KEY (MATERIAL_ID) REFERENCES TB_MATERIAL(MATERIAL_ID),
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES TB_WAREHOUSE(WAREHOUSE_ID)
);
CREATE TABLE TB_MATERIAL_INPUT (
    INPUT_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '입고 ID',
    MATERIAL_ID VARCHAR(50) NOT NULL COMMENT '자재 ID',
    WAREHOUSE_ID VARCHAR(50) NOT NULL COMMENT '입고 창고 ID',
    QUANTITY INT NOT NULL COMMENT '입고 수량',
    INPUT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '입고 일시',
    FOREIGN KEY (MATERIAL_ID) REFERENCES TB_MATERIAL(MATERIAL_ID),
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES TB_WAREHOUSE(WAREHOUSE_ID)
);
CREATE TABLE TB_MATERIAL_OUTPUT (
    OUTPUT_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '출고 ID',
    MATERIAL_ID VARCHAR(50) NOT NULL COMMENT '자재 ID',
    WAREHOUSE_ID VARCHAR(50) NOT NULL COMMENT '출고 창고 ID',
    QUANTITY INT NOT NULL COMMENT '출고 수량',
    OUTPUT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '출고 일시',
    FOREIGN KEY (MATERIAL_ID) REFERENCES TB_MATERIAL(MATERIAL_ID),
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES TB_WAREHOUSE(WAREHOUSE_ID)
);
CREATE TABLE TB_MATERIAL_LOT (
    LOT_ID VARCHAR(50) PRIMARY KEY COMMENT '자재 LOT 번호',
    MATERIAL_ID VARCHAR(50) NOT NULL COMMENT '자재 ID',
    QUANTITY INT DEFAULT 0 COMMENT 'LOT 보유 수량',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MATERIAL_ID) REFERENCES TB_MATERIAL(MATERIAL_ID)
);
CREATE TABLE TB_MATERIAL_MOVEMENT (
    MOVEMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '이동 ID',
    MATERIAL_ID VARCHAR(50) NOT NULL COMMENT '자재 ID',
    LOT_ID VARCHAR(50) COMMENT 'LOT ID',
    FROM_WAREHOUSE_ID VARCHAR(50) COMMENT '출발 창고',
    TO_WAREHOUSE_ID VARCHAR(50) COMMENT '도착 창고',
    MOVED_QUANTITY INT NOT NULL COMMENT '이동 수량',
    MOVED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '이동 시각',
    FOREIGN KEY (MATERIAL_ID) REFERENCES TB_MATERIAL(MATERIAL_ID),
    FOREIGN KEY (LOT_ID) REFERENCES TB_MATERIAL_LOT(LOT_ID)
);


