
CREATE TABLE TB_INSPECTION (
    INSPECTION_ID VARCHAR(50) PRIMARY KEY COMMENT '검사 ID',
    PROCESS_ID VARCHAR(50) NOT NULL COMMENT '공정 ID',
    ITEM_ID VARCHAR(50) NOT NULL COMMENT '품목 ID',
    INSPECTION_TYPE VARCHAR(50) NOT NULL COMMENT '검사 유형 (예: 초중종검)',
    CRITERIA TEXT COMMENT '검사 기준',
    CREATED_BY VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PROCESS_ID) REFERENCES TB_PROCESS(PROCESS_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM(ITEM_ID)
);
CREATE TABLE TB_INSPECTION_RESULT (
    RESULT_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '검사 결과 ID',
    INSPECTION_ID VARCHAR(50) NOT NULL COMMENT '검사 기준 ID',
    WORK_ORDER_ID VARCHAR(50) NOT NULL COMMENT '작업지시 ID',
    RESULT VARCHAR(50) NOT NULL COMMENT '검사 결과 (합격/불합격 등)',
    DEFECT_DESC TEXT COMMENT '결함 설명',
    INSPECTED_BY VARCHAR(50) COMMENT '검사자',
    INSPECTED_AT DATETIME COMMENT '검사 일시',
    FOREIGN KEY (INSPECTION_ID) REFERENCES TB_INSPECTION(INSPECTION_ID),
    FOREIGN KEY (WORK_ORDER_ID) REFERENCES TB_WORK_ORDER(WORK_ORDER_ID)
);
CREATE TABLE TB_DEFECT (
    DEFECT_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '불량 ID',
    RESULT_ID BIGINT NOT NULL COMMENT '검사 결과 ID',
    DEFECT_TYPE VARCHAR(50) COMMENT '불량 유형',
    ACTION_TAKEN TEXT COMMENT '조치 내용',
    FOREIGN KEY (RESULT_ID) REFERENCES TB_INSPECTION_RESULT(RESULT_ID)
);
CREATE TABLE TB_CAPA_ACTION (
    CAPA_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'CAPA ID',
    DEFECT_ID BIGINT NOT NULL COMMENT '불량 ID',
    ACTION_TYPE VARCHAR(50) COMMENT '조치 유형 (시정/예방)',
    ACTION_DETAIL TEXT COMMENT '조치 상세 내용',
    ACTION_DATE DATETIME COMMENT '조치 일시',
    ACTION_BY VARCHAR(50) COMMENT '조치자',
    FOREIGN KEY (DEFECT_ID) REFERENCES TB_DEFECT(DEFECT_ID)
);
