/* ==========================================
   GlobalMed MES • Wipe All Tables (Dev Only)
   위험: 모든 데이터 삭제/AI 초기화
   ========================================== */
SET FOREIGN_KEY_CHECKS = 0;

-- TRUNCATE TABLE TB_INT_INBOX;
-- TRUNCATE TABLE TB_INT_OUTBOX;
-- TRUNCATE TABLE TB_ERP_WO_LINK;
-- TRUNCATE TABLE TB_ERP_PROD_ORDER;

-- TRUNCATE TABLE TB_EQP_TELEMETRY;

TRUNCATE TABLE TB_ROLE_MENU;
TRUNCATE TABLE TB_MENU;
TRUNCATE TABLE TB_USER_ROLE;
TRUNCATE TABLE TB_ROLE;
TRUNCATE TABLE TB_USER;

TRUNCATE TABLE TB_AUDIT_LOG;

TRUNCATE TABLE TB_INSPECTION_RESULT;
TRUNCATE TABLE TB_NON_CONFORMANCE;
TRUNCATE TABLE TB_DEFECT;
TRUNCATE TABLE TB_INSPECTION;

TRUNCATE TABLE TB_PRODUCTION_PERFORMANCE;
TRUNCATE TABLE TB_EQUIPMENT_STATUS_LOG;

TRUNCATE TABLE TB_SHIFT_ASSIGNMENT;
TRUNCATE TABLE TB_SHIFT_CALENDAR;
TRUNCATE TABLE TB_SHIFT;

TRUNCATE TABLE TB_MATERIAL_LOT;
TRUNCATE TABLE TB_BOM;

TRUNCATE TABLE TB_WORK_ORDER;
TRUNCATE TABLE TB_PRODUCTION_PLAN;

TRUNCATE TABLE TB_EQUIPMENT;
TRUNCATE TABLE TB_WAREHOUSE;
TRUNCATE TABLE TB_ITEM;
TRUNCATE TABLE TB_PROCESS;
TRUNCATE TABLE TB_WORKCENTER;
TRUNCATE TABLE TB_WORKSHOP;

TRUNCATE TABLE TB_KPI_TARGET;

TRUNCATE TABLE TB_CODE;
TRUNCATE TABLE TB_CODE_GROUP;

-- (선택) 문서 관리가 있다면
-- TRUNCATE TABLE TB_DOCUMENT_MANAGEMENT;

SET FOREIGN_KEY_CHECKS = 1;