-- 외래 키 제약 조건 비활성화
SET FOREIGN_KEY_CHECKS = 0;

-- 1단계: 가장 하위 종속성을 가진 테이블부터 삭제
DROP TABLE IF EXISTS `TB_CAPA_ACTION`;
DROP TABLE IF EXISTS `TB_DEFECT`;
DROP TABLE IF EXISTS `TB_INSPECTION_RESULT`;
DROP TABLE IF EXISTS `TB_TRACEABILITY_LOG`;
DROP TABLE IF EXISTS `TB_SHIPPING_ORDER_ITEM`;
DROP TABLE IF EXISTS `TB_LOT_HISTORY`;
DROP TABLE IF EXISTS `TB_PRODUCTION_PERFORMANCE`;
DROP TABLE IF EXISTS `TB_DAILY_WORK_REPORT`;
DROP TABLE IF EXISTS `TB_OPERATION_LOG`;
DROP TABLE IF EXISTS `TB_PRODUCTION_ORDER`;
DROP TABLE IF EXISTS `TB_WORK_ORDER`;
DROP TABLE IF EXISTS `TB_INSPECTION`;
DROP TABLE IF EXISTS `TB_PROCESS_ROUTE`;
DROP TABLE IF EXISTS `TB_SHIPPING_ORDER`;
DROP TABLE IF EXISTS `TB_MATERIAL_MOVEMENT`;
DROP TABLE IF EXISTS `TB_MATERIAL_LOT`;
DROP TABLE IF EXISTS `TB_STOCK`;
DROP TABLE IF EXISTS `TB_MATERIAL_INPUT`;
DROP TABLE IF EXISTS `TB_MATERIAL_OUTPUT`;
DROP TABLE IF EXISTS `TB_MATERIAL`;
DROP TABLE IF EXISTS `TB_EQUIPMENT_CHECK`;
DROP TABLE IF EXISTS `TB_EQUIPMENT_MAINTENANCE_LOG`;
DROP TABLE IF EXISTS `TB_EQUIPMENT_STATUS`;
DROP TABLE IF EXISTS `TB_EQUIPMENT_SENSOR_LOG`;
DROP TABLE IF EXISTS `TB_EQUIPMENT`;
DROP TABLE IF EXISTS `TB_USER_ROLE`;
DROP TABLE IF EXISTS `TB_USER`;
DROP TABLE IF EXISTS `TB_CODE`;
DROP TABLE IF EXISTS `TB_PRODUCTION_PLAN_INTERFACE`;
DROP TABLE IF EXISTS `TB_PRODUCTION_PLAN`;

-- 2단계: 최상위 종속성 테이블 삭제
DROP TABLE IF EXISTS `TB_ITEM`;
DROP TABLE IF EXISTS `TB_PROCESS`;
DROP TABLE IF EXISTS `TB_WORKCENTER`;
DROP TABLE IF EXISTS `TB_SUPPLIER`;
DROP TABLE IF EXISTS `TB_WAREHOUSE`;
DROP TABLE IF EXISTS `TB_CUSTOMER`;
DROP TABLE IF EXISTS `TB_CODE_GROUP`;
DROP TABLE IF EXISTS `TB_ROLE`;
DROP TABLE IF EXISTS `TB_LINE`;
DROP TABLE IF EXISTS `TB_WORKPLACE`;

-- 외래 키 제약 조건 다시 활성화
SET FOREIGN_KEY_CHECKS = 1;