spring.application.name=sf_system_0001_simple_react_sb

# Mysql
spring.datasource.url=jdbc:mysql://localhost:3306/sf_system_0001_simple_react_sb
spring.datasource.username=root
spring.datasource.password=1121
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#h2
#spring.datasource.url=jdbc:h2:mem:sf_system_0001_simple_react_sb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

#h2,mysql ??
spring.jpa.hibernate.ddl=update
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=hj123451234512345123451234512345
jwt.expiration=3600000





