-- MySQL Database DDL Script for MES_DB

-- 데이터베이스 생성 (선택 사항, 이미 존재하면 생략)
CREATE DATABASE IF NOT EXISTS `MES_DB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `MES_DB`;

-- 1. TB_COMMON_CODE_GROUP (공통 코드 그룹)
CREATE TABLE `TB_COMMON_CODE_GROUP` (
    `GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '공통 코드 그룹 코드',
    `GROUP_NAME` VARCHAR(100) NOT NULL COMMENT '공통 코드 그룹명',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`GROUP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공통 코드 그룹';

-- 2. TB_COMMON_CODE (공통 코드)
CREATE TABLE `TB_COMMON_CODE` (
    `CODE_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '코드 ID',
    `GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '공통 코드 그룹 코드',
    `CODE_VALUE` VARCHAR(50) NOT NULL COMMENT '코드 값',
    `CODE_NAME` VARCHAR(100) NOT NULL COMMENT '코드명',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `SORT_ORDER` INT NULL DEFAULT 0 COMMENT '정렬 순서',
    `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`CODE_ID`),
    UNIQUE KEY `UK_GROUP_CODE_VALUE` (`GROUP_CODE`, `CODE_VALUE`),
    FOREIGN KEY (`GROUP_CODE`) REFERENCES `TB_COMMON_CODE_GROUP` (`GROUP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공통 코드';

-- 3. TB_USER (사용자 정보)
CREATE TABLE `TB_USER` (
    `USER_ID` VARCHAR(50) NOT NULL COMMENT '사용자 ID',
    `PASSWORD` VARCHAR(255) NOT NULL COMMENT '비밀번호',
    `USER_NAME` VARCHAR(100) NOT NULL COMMENT '사용자명',
    `EMAIL` VARCHAR(100) NULL COMMENT '이메일',
    `PHONE_NUMBER` VARCHAR(20) NULL COMMENT '연락처',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 정보';

-- 4. TB_ROLE (역할/권한)
CREATE TABLE `TB_ROLE` (
    `ROLE_ID` VARCHAR(50) NOT NULL COMMENT '역할 ID',
    `ROLE_NAME` VARCHAR(100) NOT NULL COMMENT '역할명',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='역할/권한';

-- 5. TB_ORGANIZATION (조직 정보)
CREATE TABLE `TB_ORGANIZATION` (
    `ORG_ID` VARCHAR(50) NOT NULL COMMENT '조직 ID',
    `ORG_NAME` VARCHAR(100) NOT NULL COMMENT '조직명',
    `PARENT_ORG_ID` VARCHAR(50) NULL COMMENT '상위 조직 ID',
    `ORG_TYPE` VARCHAR(50) NULL COMMENT '조직 유형 (예: 부서, 팀, 공장 등)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ORG_ID`),
    FOREIGN KEY (`PARENT_ORG_ID`) REFERENCES `TB_ORGANIZATION` (`ORG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='조직 정보';

-- 6. TB_SYSTEM_MENU (시스템 메뉴)
CREATE TABLE `TB_SYSTEM_MENU` (
    `MENU_ID` VARCHAR(50) NOT NULL COMMENT '메뉴 ID',
    `MENU_NAME` VARCHAR(100) NOT NULL COMMENT '메뉴명',
    `PARENT_MENU_ID` VARCHAR(50) NULL COMMENT '상위 메뉴 ID',
    `MENU_URL` VARCHAR(255) NULL COMMENT '메뉴 URL',
    `MENU_ORDER` INT NULL DEFAULT 0 COMMENT '메뉴 순서',
    `ICON` VARCHAR(50) NULL COMMENT '아이콘',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`MENU_ID`),
    FOREIGN KEY (`PARENT_MENU_ID`) REFERENCES `TB_SYSTEM_MENU` (`MENU_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='시스템 메뉴';

-- 7. TB_MENU_ROLE_MAPPING (메뉴 역할 매핑)
CREATE TABLE `TB_MENU_ROLE_MAPPING` (
    `MAPPING_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '매핑 ID',
    `MENU_ID` VARCHAR(50) NOT NULL COMMENT '메뉴 ID',
    `ROLE_ID` VARCHAR(50) NOT NULL COMMENT '역할 ID',
    `CAN_VIEW` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '조회 가능 여부',
    `CAN_EDIT` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '편집 가능 여부',
    `CAN_DELETE` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 가능 여부',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`MAPPING_ID`),
    UNIQUE KEY `UK_MENU_ROLE` (`MENU_ID`, `ROLE_ID`),
    FOREIGN KEY (`MENU_ID`) REFERENCES `TB_SYSTEM_MENU` (`MENU_ID`),
    FOREIGN KEY (`ROLE_ID`) REFERENCES `TB_ROLE` (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='메뉴 역할 매핑';

-- 8. TB_ITEM (품목 마스터)
CREATE TABLE `TB_ITEM` (
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `ITEM_NAME` VARCHAR(200) NOT NULL COMMENT '품목명',
    `ITEM_TYPE` VARCHAR(50) NOT NULL COMMENT '품목 유형 (제품, 반제품, 원자재, 부자재)',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '기본 단위',
    `SPECIFICATION` VARCHAR(255) NULL COMMENT '규격',
    `DESCRIPTION` VARCHAR(500) NULL COMMENT '설명',
    `SAFETY_STOCK_QTY` DECIMAL(10,4) NULL DEFAULT 0 COMMENT '안전 재고 수량',
    `LEAD_TIME_DAYS` INT NULL DEFAULT 0 COMMENT '리드 타임 (일)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='품목 마스터';

-- 9. TB_MES_BOM (BOM 마스터)
CREATE TABLE `TB_MES_BOM` (
    `BOM_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'BOM ID',
    `PARENT_ITEM_ID` VARCHAR(50) NOT NULL COMMENT '상위 품목 ID',
    `CHILD_ITEM_ID` VARCHAR(50) NOT NULL COMMENT '하위 품목 ID',
    `QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '소요 수량',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `START_DATE` DATE NULL COMMENT '유효 시작일',
    `END_DATE` DATE NULL COMMENT '유효 종료일',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`BOM_ID`),
    UNIQUE KEY `UK_PARENT_CHILD` (`PARENT_ITEM_ID`, `CHILD_ITEM_ID`),
    FOREIGN KEY (`PARENT_ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`CHILD_ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='BOM 마스터';

-- 10. TB_COMPONENT_PRODUCT_MAPPING (원자재-제품 매핑)
CREATE TABLE `TB_COMPONENT_PRODUCT_MAPPING` (
    `MAPPING_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '매핑 ID',
    `COMPONENT_ITEM_ID` VARCHAR(50) NOT NULL COMMENT '원자재 품목 ID',
    `PRODUCT_ITEM_ID` VARCHAR(50) NOT NULL COMMENT '제품 품목 ID',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`MAPPING_ID`),
    UNIQUE KEY `UK_COMPONENT_PRODUCT` (`COMPONENT_ITEM_ID`, `PRODUCT_ITEM_ID`),
    FOREIGN KEY (`COMPONENT_ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`PRODUCT_ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='원자재-제품 매핑';

-- 11. TB_ROUTE (공정 라우팅)
CREATE TABLE `TB_ROUTE` (
    `ROUTE_ID` VARCHAR(50) NOT NULL COMMENT '라우팅 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `ROUTE_NAME` VARCHAR(100) NOT NULL COMMENT '라우팅명',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ROUTE_ID`),
    UNIQUE KEY `UK_ITEM_ID` (`ITEM_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공정 라우팅';

-- 12. TB_WORKPLACE (작업장 마스터)
CREATE TABLE `TB_WORKPLACE` (
    `WORKPLACE_ID` VARCHAR(50) NOT NULL COMMENT '작업장 ID',
    `WORKPLACE_NAME` VARCHAR(100) NOT NULL COMMENT '작업장명',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `LOCATION` VARCHAR(100) NULL COMMENT '위치',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`WORKPLACE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='작업장 마스터';

-- 13. TB_ROUTE_OPERATION (라우팅 공정)
CREATE TABLE `TB_ROUTE_OPERATION` (
    `OPERATION_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '공정 ID',
    `ROUTE_ID` VARCHAR(50) NOT NULL COMMENT '라우팅 ID',
    `OPERATION_CODE` VARCHAR(50) NOT NULL COMMENT '공정 코드',
    `OPERATION_NAME` VARCHAR(100) NOT NULL COMMENT '공정명',
    `WORKPLACE_ID` VARCHAR(50) NOT NULL COMMENT '작업장 ID',
    `SEQUENCE` INT NOT NULL COMMENT '공정 순서',
    `STANDARD_TIME_PER_UNIT` DECIMAL(10,4) NULL COMMENT '단위당 표준 시간',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`OPERATION_ID`),
    UNIQUE KEY `UK_ROUTE_SEQUENCE` (`ROUTE_ID`, `SEQUENCE`),
    FOREIGN KEY (`ROUTE_ID`) REFERENCES `TB_ROUTE` (`ROUTE_ID`),
    FOREIGN KEY (`WORKPLACE_ID`) REFERENCES `TB_WORKPLACE` (`WORKPLACE_ID`),
    FOREIGN KEY (`OPERATION_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 공정 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='라우팅 공정';

-- 14. TB_LINE (생산 라인)
CREATE TABLE `TB_LINE` (
    `LINE_ID` VARCHAR(50) NOT NULL COMMENT '라인 ID',
    `LINE_NAME` VARCHAR(100) NOT NULL COMMENT '라인명',
    `WORKPLACE_ID` VARCHAR(50) NOT NULL COMMENT '속한 작업장 ID',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`LINE_ID`),
    FOREIGN KEY (`WORKPLACE_ID`) REFERENCES `TB_WORKPLACE` (`WORKPLACE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='생산 라인';

-- 15. TB_EQUIPMENT (설비 마스터)
CREATE TABLE `TB_EQUIPMENT` (
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `EQUIP_NAME` VARCHAR(100) NOT NULL COMMENT '설비명',
    `LINE_ID` VARCHAR(50) NOT NULL COMMENT '속한 라인 ID',
    `EQUIP_TYPE` VARCHAR(50) NULL COMMENT '설비 유형 (예: 성형기, 조립기, 검사기)',
    `MODEL_NO` VARCHAR(100) NULL COMMENT '모델 번호',
    `SERIAL_NO` VARCHAR(100) NULL COMMENT '시리얼 번호',
    `INSTALL_DATE` DATE NULL COMMENT '설치 일자',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`EQUIP_ID`),
    FOREIGN KEY (`LINE_ID`) REFERENCES `TB_LINE` (`LINE_ID`),
    FOREIGN KEY (`EQUIP_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 설비 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='설비 마스터';

-- 16. TB_EQUIPMENT_SENSOR_DATA (설비 센서 데이터)
CREATE TABLE `TB_EQUIPMENT_SENSOR_DATA` (
    `DATA_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '데이터 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `SENSOR_TYPE` VARCHAR(50) NOT NULL COMMENT '센서 유형 (온도, 압력, 진동 등)',
    `SENSOR_VALUE` DECIMAL(18,4) NOT NULL COMMENT '센서 값',
    `UNIT` VARCHAR(10) NULL COMMENT '단위',
    `COLLECTION_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '데이터 수집 시간',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`DATA_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='설비 센서 데이터';

-- 17. TB_DOWNTIME_EVENT (설비 비가동 이벤트)
CREATE TABLE `TB_DOWNTIME_EVENT` (
    `DOWNTIME_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '비가동 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `DOWNTIME_START_TIME` DATETIME NOT NULL COMMENT '비가동 시작 시간',
    `DOWNTIME_END_TIME` DATETIME NULL COMMENT '비가동 종료 시간',
    `DOWNTIME_CODE` VARCHAR(50) NOT NULL COMMENT '비가동 코드 (정전, 고장, 점검, 대기 등)',
    `REASON_DETAIL` VARCHAR(255) NULL COMMENT '상세 사유',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`DOWNTIME_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`),
    FOREIGN KEY (`DOWNTIME_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 비가동 사유 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='설비 비가동 이벤트';

-- 18. TB_EQUIPMENT_STATUS (설비 상태)
CREATE TABLE `TB_EQUIPMENT_STATUS` (
    `EQUIP_STATUS_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '설비 상태 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `STATUS_TYPE_CODE` VARCHAR(50) NOT NULL COMMENT '상태 유형 (운전, 대기, 고장, 비가동 등)',
    `STATUS_MESSAGE` VARCHAR(255) NULL COMMENT '상세 상태 메시지',
    `LAST_UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 상태 업데이트 일시',
    `CURRENT_ALARM_CODE` VARCHAR(50) NULL COMMENT '현재 발생 중인 알람 코드',
    `IS_RUNNING` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '가동 여부 (Y/N)',
    `DAILY_RUN_TIME` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '금일 가동 시간 (분)',
    `DAILY_DOWNTIME` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '금일 비가동 시간 (분)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`EQUIP_STATUS_ID`),
    UNIQUE KEY `UK_EQUIP_ID` (`EQUIP_ID`), -- 설비별 최신 상태는 하나만 존재
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`),
    FOREIGN KEY (`STATUS_TYPE_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 설비 상태 유형 참조
    FOREIGN KEY (`CURRENT_ALARM_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 알람 코드 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='설비 상태';

-- 19. TB_MATERIAL_INVENTORY (자재 재고)
CREATE TABLE `TB_MATERIAL_INVENTORY` (
    `INVENTORY_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '재고 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT 'Lot 번호',
    `WAREHOUSE_CODE` VARCHAR(50) NOT NULL COMMENT '창고 코드',
    `LOCATION_CODE` VARCHAR(50) NULL COMMENT '창고 위치 코드',
    `CURRENT_QTY` DECIMAL(10,4) NOT NULL COMMENT '현재 재고 수량',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `LAST_UPDATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 업데이트 일시',
    `EXPIRATION_DATE` DATE NULL COMMENT '유효 기간',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`INVENTORY_ID`),
    UNIQUE KEY `UK_ITEM_LOT_WAREHOUSE_LOCATION` (`ITEM_ID`, `LOT_NO`, `WAREHOUSE_CODE`, `LOCATION_CODE`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`WAREHOUSE_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 창고 코드 참조
    FOREIGN KEY (`LOCATION_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 창고 위치 코드 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='자재 재고';

-- 20. TB_WIP (재공품 현황)
CREATE TABLE `TB_WIP` (
    `WIP_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '재공품 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT 'Lot 번호',
    `CURRENT_QTY` DECIMAL(10,4) NOT NULL COMMENT '현재 재공 수량',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `CURRENT_OPERATION_CODE` VARCHAR(50) NOT NULL COMMENT '현재 공정 코드',
    `CURRENT_WORKPLACE_ID` VARCHAR(50) NOT NULL COMMENT '현재 작업장 ID',
    `CURRENT_EQUIP_ID` VARCHAR(50) NULL COMMENT '현재 설비 ID',
    `LAST_UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 업데이트 일시',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`WIP_ID`),
    UNIQUE KEY `UK_ITEM_LOT_OPERATION_WORKPLACE` (`ITEM_ID`, `LOT_NO`, `CURRENT_OPERATION_CODE`, `CURRENT_WORKPLACE_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`CURRENT_OPERATION_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 공정 유형 참조
    FOREIGN KEY (`CURRENT_WORKPLACE_ID`) REFERENCES `TB_WORKPLACE` (`WORKPLACE_ID`),
    FOREIGN KEY (`CURRENT_EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='재공품 현황';

-- 21. TB_PRODUCTION_PLAN (생산 계획)
CREATE TABLE `TB_PRODUCTION_PLAN` (
    `PLAN_ID` VARCHAR(50) NOT NULL COMMENT '계획 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `PLAN_DATE` DATE NOT NULL COMMENT '계획 일자',
    `PLAN_QTY` DECIMAL(10,4) NOT NULL COMMENT '계획 수량',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `LINE_ID` VARCHAR(50) NULL COMMENT '계획 생산 라인 ID',
    `PLAN_STATUS` VARCHAR(20) NOT NULL COMMENT '계획 상태 (예: 예정, 진행중, 완료, 취소)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`PLAN_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`LINE_ID`) REFERENCES `TB_LINE` (`LINE_ID`),
    FOREIGN KEY (`PLAN_STATUS`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 계획 상태 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='생산 계획';

-- 22. TB_PRODUCTION_PLAN_INTERFACE (생산 계획 인터페이스)
CREATE TABLE `TB_PRODUCTION_PLAN_INTERFACE` (
    `INTERFACE_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '인터페이스 ID',
    `SOURCE_SYSTEM` VARCHAR(50) NOT NULL COMMENT '소스 시스템 (예: ERP)',
    `SOURCE_PLAN_ID` VARCHAR(50) NOT NULL COMMENT '소스 시스템의 계획 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `PLAN_DATE` DATE NOT NULL COMMENT '계획 일자',
    `PLAN_QTY` DECIMAL(10,4) NOT NULL COMMENT '계획 수량',
    `LINE_ID` VARCHAR(50) NULL COMMENT '계획 생산 라인 ID',
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'NEW' COMMENT '처리 상태 (NEW, PROCESSED, ERROR)',
    `ERROR_MESSAGE` VARCHAR(500) NULL COMMENT '오류 메시지',
    `INTERFACE_DATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '인터페이스 수신 일시',
    `PROCESSED_DATE_TIME` DATETIME NULL COMMENT '처리 완료 일시',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`INTERFACE_ID`),
    UNIQUE KEY `UK_SOURCE_SYSTEM_PLAN_ID` (`SOURCE_SYSTEM`, `SOURCE_PLAN_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`LINE_ID`) REFERENCES `TB_LINE` (`LINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='생산 계획 인터페이스';

-- 23. TB_WORK_ORDER (작업 지시)
CREATE TABLE `TB_WORK_ORDER` (
    `WORK_ORDER_ID` VARCHAR(50) NOT NULL COMMENT '작업 지시 ID',
    `PLAN_ID` VARCHAR(50) NOT NULL COMMENT '관련 생산 계획 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `ORDER_QTY` DECIMAL(10,4) NOT NULL COMMENT '지시 수량',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `DUE_DATE` DATE NOT NULL COMMENT '완료 예정일',
    `LINE_ID` VARCHAR(50) NOT NULL COMMENT '생산 라인 ID',
    `WORKPLACE_ID` VARCHAR(50) NOT NULL COMMENT '작업장 ID',
    `ORDER_STATUS` VARCHAR(20) NOT NULL COMMENT '지시 상태 (예: 발행, 진행중, 완료, 보류, 취소)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`WORK_ORDER_ID`),
    FOREIGN KEY (`PLAN_ID`) REFERENCES `TB_PRODUCTION_PLAN` (`PLAN_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`LINE_ID`) REFERENCES `TB_LINE` (`LINE_ID`),
    FOREIGN KEY (`WORKPLACE_ID`) REFERENCES `TB_WORKPLACE` (`WORKPLACE_ID`),
    FOREIGN KEY (`ORDER_STATUS`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 작업 지시 상태 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='작업 지시';

-- 24. TB_PRODUCTION_PERFORMANCE (생산 실적)
CREATE TABLE `TB_PRODUCTION_PERFORMANCE` (
    `PERFORMANCE_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '실적 ID',
    `WORK_ORDER_ID` VARCHAR(50) NOT NULL COMMENT '작업 지시 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT 'Lot 번호',
    `PRODUCED_QTY` DECIMAL(10,4) NOT NULL COMMENT '생산 수량',
    `GOOD_QTY` DECIMAL(10,4) NOT NULL COMMENT '양품 수량',
    `DEFECT_QTY` DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT '불량 수량',
    `PRODUCTION_START_TIME` DATETIME NOT NULL COMMENT '생산 시작 시간',
    `PRODUCTION_END_TIME` DATETIME NOT NULL COMMENT '생산 종료 시간',
    `LINE_ID` VARCHAR(50) NOT NULL COMMENT '생산 라인 ID',
    `WORKPLACE_ID` VARCHAR(50) NOT NULL COMMENT '작업장 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `OPERATOR_USER_ID` VARCHAR(50) NOT NULL COMMENT '작업자 사용자 ID',
    `OPERATION_CODE` VARCHAR(50) NOT NULL COMMENT '수행 공정 코드',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`PERFORMANCE_ID`),
    FOREIGN KEY (`WORK_ORDER_ID`) REFERENCES `TB_WORK_ORDER` (`WORK_ORDER_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`LINE_ID`) REFERENCES `TB_LINE` (`LINE_ID`),
    FOREIGN KEY (`WORKPLACE_ID`) REFERENCES `TB_WORKPLACE` (`WORKPLACE_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`),
    FOREIGN KEY (`OPERATOR_USER_ID`) REFERENCES `TB_USER` (`USER_ID`),
    FOREIGN KEY (`OPERATION_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 공정 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='생산 실적';

-- 25. TB_MATERIAL_CONSUMPTION (자재 소모)
CREATE TABLE `TB_MATERIAL_CONSUMPTION` (
    `CONSUMPTION_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '소모 ID',
    `PERFORMANCE_ID` BIGINT NOT NULL COMMENT '관련 생산 실적 ID',
    `CONSUMED_ITEM_ID` VARCHAR(50) NOT NULL COMMENT '소모된 품목 ID',
    `CONSUMED_LOT_NO` VARCHAR(100) NOT NULL COMMENT '소모된 Lot 번호',
    `CONSUMED_QTY` DECIMAL(10,4) NOT NULL COMMENT '소모 수량',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `CONSUMPTION_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '소모 일시',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`CONSUMPTION_ID`),
    FOREIGN KEY (`PERFORMANCE_ID`) REFERENCES `TB_PRODUCTION_PERFORMANCE` (`PERFORMANCE_ID`),
    FOREIGN KEY (`CONSUMED_ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='자재 소모';

-- 26. TB_FINISHED_GOODS_RECEIPT (완제품 입고)
CREATE TABLE `TB_FINISHED_GOODS_RECEIPT` (
    `FG_RECEIPT_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '완제품 입고 ID',
    `PERFORMANCE_ID` BIGINT NOT NULL COMMENT '관련 생산 실적 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '완제품 품목 ID',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT '완제품 Lot 번호',
    `SERIAL_NO` VARCHAR(100) NULL COMMENT '완제품 Serial 번호',
    `RECEIVED_QTY` DECIMAL(10,4) NOT NULL COMMENT '입고 수량',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `RECEIPT_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입고 일시',
    `WAREHOUSE_CODE` VARCHAR(50) NOT NULL COMMENT '입고 창고 코드',
    `LOCATION_CODE` VARCHAR(50) NULL COMMENT '창고 위치 코드',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`FG_RECEIPT_ID`),
    FOREIGN KEY (`PERFORMANCE_ID`) REFERENCES `TB_PRODUCTION_PERFORMANCE` (`PERFORMANCE_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`WAREHOUSE_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 창고 코드 참조
    FOREIGN KEY (`LOCATION_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 창고 위치 코드 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='완제품 입고';

-- 27. TB_DEFECT_RECORD (불량 기록)
CREATE TABLE `TB_DEFECT_RECORD` (
    `DEFECT_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '불량 ID',
    `PERFORMANCE_ID` BIGINT NULL COMMENT '관련 생산 실적 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID (불량 발생 품목)',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT '불량 Lot 번호',
    `SERIAL_NO` VARCHAR(100) NULL COMMENT '불량 Serial 번호',
    `DEFECT_QTY` DECIMAL(10,4) NOT NULL COMMENT '불량 수량',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `DEFECT_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '불량 발생 일시',
    `DEFECT_CODE` VARCHAR(50) NOT NULL COMMENT '불량 유형 코드',
    `DEFECT_REASON_CODE` VARCHAR(50) NULL COMMENT '불량 원인 코드',
    `REPORTED_BY_USER_ID` VARCHAR(50) NOT NULL COMMENT '불량 보고자 ID',
    `OPERATION_CODE` VARCHAR(50) NULL COMMENT '불량 발생 공정 코드',
    `WORKPLACE_ID` VARCHAR(50) NULL COMMENT '불량 발생 작업장 ID',
    `EQUIP_ID` VARCHAR(50) NULL COMMENT '불량 발생 설비 ID',
    `VENDOR_ID` VARCHAR(50) NULL COMMENT '관련 업체 ID (자재 불량의 경우)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`DEFECT_ID`),
    FOREIGN KEY (`PERFORMANCE_ID`) REFERENCES `TB_PRODUCTION_PERFORMANCE` (`PERFORMANCE_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`DEFECT_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 불량 유형 참조
    FOREIGN KEY (`DEFECT_REASON_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 불량 원인 참조
    FOREIGN KEY (`REPORTED_BY_USER_ID`) REFERENCES `TB_USER` (`USER_ID`),
    FOREIGN KEY (`OPERATION_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 공정 유형 참조
    FOREIGN KEY (`WORKPLACE_ID`) REFERENCES `TB_WORKPLACE` (`WORKPLACE_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`),
    FOREIGN KEY (`VENDOR_ID`) REFERENCES `TB_VENDOR` (`VENDOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='불량 기록';

-- 28. TB_DEFECT_ACTION_HISTORY (불량 조치 이력)
CREATE TABLE `TB_DEFECT_ACTION_HISTORY` (
    `ACTION_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '조치 ID',
    `DEFECT_ID` BIGINT NOT NULL COMMENT '불량 ID',
    `ACTION_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '조치 일시',
    `ACTION_TYPE_CODE` VARCHAR(50) NOT NULL COMMENT '조치 유형 코드 (수정, 폐기, 재작업 등)',
    `ACTION_DESCRIPTION` VARCHAR(500) NULL COMMENT '조치 상세 내용',
    `ACTION_BY_USER_ID` VARCHAR(50) NOT NULL COMMENT '조치자 ID',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ACTION_ID`),
    FOREIGN KEY (`DEFECT_ID`) REFERENCES `TB_DEFECT_RECORD` (`DEFECT_ID`),
    FOREIGN KEY (`ACTION_TYPE_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 불량 조치 유형 참조
    FOREIGN KEY (`ACTION_BY_USER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='불량 조치 이력';

-- 29. TB_DAILY_WORK_REPORT (일일 작업 보고서)
CREATE TABLE `TB_DAILY_WORK_REPORT` (
    `REPORT_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '보고서 ID',
    `REPORT_DATE` DATE NOT NULL COMMENT '보고 일자',
    `LINE_ID` VARCHAR(50) NOT NULL COMMENT '라인 ID',
    `WORKPLACE_ID` VARCHAR(50) NOT NULL COMMENT '작업장 ID',
    `SHIFT_CODE` VARCHAR(50) NOT NULL COMMENT '쉬프트 코드 (주간, 야간 등)',
    `TOTAL_PRODUCTION_QTY` DECIMAL(10,4) NOT NULL COMMENT '총 생산 수량',
    `TOTAL_GOOD_QTY` DECIMAL(10,4) NOT NULL COMMENT '총 양품 수량',
    `TOTAL_DEFECT_QTY` DECIMAL(10,4) NOT NULL COMMENT '총 불량 수량',
    `TOTAL_RUN_TIME` DECIMAL(10,2) NOT NULL COMMENT '총 가동 시간 (분)',
    `TOTAL_DOWNTIME` DECIMAL(10,2) NOT NULL COMMENT '총 비가동 시간 (분)',
    `REPORTED_BY_USER_ID` VARCHAR(50) NOT NULL COMMENT '보고자 ID',
    `REMARKS` VARCHAR(500) NULL COMMENT '비고',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`REPORT_ID`),
    UNIQUE KEY `UK_REPORT_DATE_LINE_SHIFT` (`REPORT_DATE`, `LINE_ID`, `SHIFT_CODE`),
    FOREIGN KEY (`LINE_ID`) REFERENCES `TB_LINE` (`LINE_ID`),
    FOREIGN KEY (`WORKPLACE_ID`) REFERENCES `TB_WORKPLACE` (`WORKPLACE_ID`),
    FOREIGN KEY (`SHIFT_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 쉬프트 코드 참조
    FOREIGN KEY (`REPORTED_BY_USER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='일일 작업 보고서';

-- 30. TB_QUALITY_INSPECTION_PLAN (품질 검사 계획)
CREATE TABLE `TB_QUALITY_INSPECTION_PLAN` (
    `INSPECTION_PLAN_ID` VARCHAR(50) NOT NULL COMMENT '검사 계획 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `INSPECTION_TYPE_CODE` VARCHAR(50) NOT NULL COMMENT '검사 유형 코드 (수입 검사, 공정 검사, 최종 검사)',
    `INSPECTION_METHOD` VARCHAR(255) NULL COMMENT '검사 방법',
    `INSPECTION_FREQUENCY_CODE` VARCHAR(50) NULL COMMENT '검사 주기 코드',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`INSPECTION_PLAN_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`INSPECTION_TYPE_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 검사 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='품질 검사 계획';

-- 31. TB_QUALITY_INSPECTION_CRITERIA (품질 검사 기준)
CREATE TABLE `TB_QUALITY_INSPECTION_CRITERIA` (
    `CRITERIA_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '기준 ID',
    `INSPECTION_PLAN_ID` VARCHAR(50) NOT NULL COMMENT '검사 계획 ID',
    `CRITERIA_NAME` VARCHAR(100) NOT NULL COMMENT '검사 항목명',
    `CRITERIA_TYPE_CODE` VARCHAR(50) NOT NULL COMMENT '기준 유형 (정량, 정성)',
    `STANDARD_VALUE` VARCHAR(100) NULL COMMENT '표준 값',
    `UPPER_LIMIT` DECIMAL(18,4) NULL COMMENT '상한치 (정량)',
    `LOWER_LIMIT` DECIMAL(18,4) NULL COMMENT '하한치 (정량)',
    `UNIT` VARCHAR(10) NULL COMMENT '단위 (정량)',
    `IS_CRITICAL` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '치명 결함 여부',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`CRITERIA_ID`),
    FOREIGN KEY (`INSPECTION_PLAN_ID`) REFERENCES `TB_QUALITY_INSPECTION_PLAN` (`INSPECTION_PLAN_ID`),
    FOREIGN KEY (`CRITERIA_TYPE_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 검사 기준 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='품질 검사 기준';

-- 32. TB_QUALITY_INSPECTION_RESULT (품질 검사 결과)
CREATE TABLE `TB_QUALITY_INSPECTION_RESULT` (
    `RESULT_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '결과 ID',
    `INSPECTION_PLAN_ID` VARCHAR(50) NOT NULL COMMENT '관련 검사 계획 ID',
    `PERFORMANCE_ID` BIGINT NULL COMMENT '관련 생산 실적 ID (공정/최종 검사)',
    `MATERIAL_RECEIPT_ID` VARCHAR(50) NULL COMMENT '관련 자재 입고 ID (수입 검사)',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT 'Lot 번호',
    `SERIAL_NO` VARCHAR(100) NULL COMMENT 'Serial 번호',
    `INSPECTION_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '검사 일시',
    `INSPECTOR_USER_ID` VARCHAR(50) NOT NULL COMMENT '검사자 ID',
    `OVERALL_RESULT_CODE` VARCHAR(50) NOT NULL COMMENT '종합 판정 코드 (합격, 불합격)',
    `ACTUAL_VALUE` VARCHAR(255) NULL COMMENT '실측 값 (정량)',
    `MEASUREMENT_UNIT` VARCHAR(10) NULL COMMENT '측정 단위',
    `REMARKS` VARCHAR(500) NULL COMMENT '비고',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`RESULT_ID`),
    FOREIGN KEY (`INSPECTION_PLAN_ID`) REFERENCES `TB_QUALITY_INSPECTION_PLAN` (`INSPECTION_PLAN_ID`),
    FOREIGN KEY (`PERFORMANCE_ID`) REFERENCES `TB_PRODUCTION_PERFORMANCE` (`PERFORMANCE_ID`),
    FOREIGN KEY (`MATERIAL_RECEIPT_ID`) REFERENCES `TB_MATERIAL_RECEIPT` (`RECEIPT_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`INSPECTOR_USER_ID`) REFERENCES `TB_USER` (`USER_ID`),
    FOREIGN KEY (`OVERALL_RESULT_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 검사 결과 코드 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='품질 검사 결과';

-- 33. TB_MOVEMENT_HISTORY (재공품/자재 이동 이력)
CREATE TABLE `TB_MOVEMENT_HISTORY` (
    `MOVEMENT_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '이동 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT 'Lot 번호',
    `SERIAL_NO` VARCHAR(100) NULL COMMENT 'Serial 번호',
    `MOVEMENT_TYPE` VARCHAR(50) NOT NULL COMMENT '이동 유형 (창고이동, 공정이동, 입고, 출고 등)',
    `FROM_LOCATION_TYPE` VARCHAR(50) NULL COMMENT '출발지 유형 (창고, 작업장)',
    `FROM_LOCATION_ID` VARCHAR(50) NULL COMMENT '출발지 ID',
    `TO_LOCATION_TYPE` VARCHAR(50) NULL COMMENT '도착지 유형 (창고, 작업장)',
    `TO_LOCATION_ID` VARCHAR(50) NULL COMMENT '도착지 ID',
    `MOVEMENT_QTY` DECIMAL(10,4) NOT NULL COMMENT '이동 수량',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `MOVEMENT_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '이동 일시',
    `MOVED_BY_USER_ID` VARCHAR(50) NOT NULL COMMENT '이동 처리자 ID',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`MOVEMENT_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`MOVED_BY_USER_ID`) REFERENCES `TB_USER` (`USER_ID`),
    FOREIGN KEY (`MOVEMENT_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 이동 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='재공품/자재 이동 이력';

-- 34. TB_LOT_HISTORY (Lot 이력)
CREATE TABLE `TB_LOT_HISTORY` (
    `HISTORY_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '이력 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT 'Lot 번호',
    `SERIAL_NO` VARCHAR(100) NULL COMMENT 'Serial 번호',
    `EVENT_TYPE` VARCHAR(50) NOT NULL COMMENT '이벤트 유형 (생산, 자재투입, 이동, 불량, 검사 등)',
    `EVENT_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '이벤트 발생 일시',
    `EVENT_USER_ID` VARCHAR(50) NULL COMMENT '이벤트 발생 사용자 ID',
    `OPERATION_CODE` VARCHAR(50) NULL COMMENT '관련 공정 코드',
    `WORKPLACE_ID` VARCHAR(50) NULL COMMENT '관련 작업장 ID',
    `EQUIP_ID` VARCHAR(50) NULL COMMENT '관련 설비 ID',
    `QUANTITY_CHANGE` DECIMAL(10,4) NULL COMMENT '수량 변화 (+/-)',
    `CURRENT_QUANTITY` DECIMAL(10,4) NULL COMMENT '해당 Lot/Serial의 현재 수량',
    `REF_TABLE_NAME` VARCHAR(50) NULL COMMENT '참조 테이블 명 (예: TB_PRODUCTION_PERFORMANCE)',
    `REF_ID` VARCHAR(50) NULL COMMENT '참조 테이블의 PK 값',
    `DESCRIPTION` VARCHAR(500) NULL COMMENT '상세 설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`HISTORY_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`EVENT_USER_ID`) REFERENCES `TB_USER` (`USER_ID`),
    FOREIGN KEY (`OPERATION_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`),
    FOREIGN KEY (`WORKPLACE_ID`) REFERENCES `TB_WORKPLACE` (`WORKPLACE_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`),
    FOREIGN KEY (`EVENT_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 이벤트 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Lot 이력';

-- 35. TB_LOT_TRACKING (Lot 추적 상세)
CREATE TABLE `TB_LOT_TRACKING` (
    `TRACKING_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '추적 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT 'Lot 번호',
    `SERIAL_NO` VARCHAR(100) NULL COMMENT 'Serial 번호',
    `CURRENT_STATUS` VARCHAR(50) NOT NULL COMMENT '현재 상태 (생산 중, 대기, 이동 중, 완료, 불량 등)',
    `CURRENT_LOCATION_TYPE` VARCHAR(50) NULL COMMENT '현재 위치 유형 (작업장, 창고, 라인 등)',
    `CURRENT_LOCATION_ID` VARCHAR(50) NULL COMMENT '현재 위치 ID (작업장ID, 창고ID 등)',
    `LAST_EVENT_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 이벤트 발생 시간',
    `LAST_EVENT_TYPE` VARCHAR(50) NULL COMMENT '최종 이벤트 유형',
    `INSPECTION_STATUS` VARCHAR(50) NOT NULL DEFAULT 'N/A' COMMENT '품질 검사 상태 (PASS, FAIL, N/A)',
    `HOLD_STATUS` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '보류 상태 (Y/N)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`TRACKING_ID`),
    UNIQUE KEY `UK_ITEM_LOT_SERIAL` (`ITEM_ID`, `LOT_NO`, `SERIAL_NO`), -- (SERIAL_NO가 NULL일 경우 Lot으로 UNIQUE)
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`CURRENT_STATUS`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 현재 상태 참조
    FOREIGN KEY (`CURRENT_LOCATION_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 위치 유형 참조
    FOREIGN KEY (`LAST_EVENT_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 이벤트 유형 참조
    FOREIGN KEY (`INSPECTION_STATUS`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 검사 상태 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Lot 추적 상세';

-- 36. TB_ANNOUNCEMENT (공지사항)
CREATE TABLE `TB_ANNOUNCEMENT` (
    `ANNOUNCEMENT_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '공지사항 ID',
    `TITLE` VARCHAR(200) NOT NULL COMMENT '제목',
    `CONTENT` TEXT NOT NULL COMMENT '내용',
    `POSTED_BY_USER_ID` VARCHAR(50) NOT NULL COMMENT '게시자 ID',
    `POST_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '게시 일시',
    `START_DATE` DATETIME NULL COMMENT '게시 시작일',
    `END_DATE` DATETIME NULL COMMENT '게시 종료일',
    `IS_IMPORTANT` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '중요 공지 여부',
    `VIEW_COUNT` INT NOT NULL DEFAULT 0 COMMENT '조회수',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ANNOUNCEMENT_ID`),
    FOREIGN KEY (`POSTED_BY_USER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공지사항';

-- 37. TB_NOTIFICATION (알림)
CREATE TABLE `TB_NOTIFICATION` (
    `NOTIFICATION_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '알림 ID',
    `USER_ID` VARCHAR(50) NOT NULL COMMENT '수신 사용자 ID',
    `NOTIFICATION_TYPE` VARCHAR(50) NOT NULL COMMENT '알림 유형 (시스템, 긴급, 경고, 정보)',
    `MESSAGE` VARCHAR(500) NOT NULL COMMENT '알림 메시지',
    `IS_READ` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '읽음 여부',
    `SENT_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '발송 일시',
    `RELATED_ENTITY_TYPE` VARCHAR(50) NULL COMMENT '관련 엔티티 유형 (예: DOWNTIME, DEFECT)',
    `RELATED_ENTITY_ID` VARCHAR(50) NULL COMMENT '관련 엔티티 ID',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`NOTIFICATION_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `TB_USER` (`USER_ID`),
    FOREIGN KEY (`NOTIFICATION_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 알림 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='알림';

-- 38. TB_VENDOR (업체 정보)
CREATE TABLE `TB_VENDOR` (
    `VENDOR_ID` VARCHAR(50) NOT NULL COMMENT '업체 ID',
    `VENDOR_NAME` VARCHAR(200) NOT NULL COMMENT '업체명',
    `VENDOR_TYPE` VARCHAR(50) NULL COMMENT '업체 유형 (원자재 공급사, 외주 가공 등)',
    `CONTACT_PERSON` VARCHAR(100) NULL COMMENT '담당자',
    `PHONE_NUMBER` VARCHAR(20) NULL COMMENT '연락처',
    `ADDRESS` VARCHAR(255) NULL COMMENT '주소',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`VENDOR_ID`),
    FOREIGN KEY (`VENDOR_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 업체 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='업체 정보';

-- 39. TB_MATERIAL_RECEIPT (자재 입고)
CREATE TABLE `TB_MATERIAL_RECEIPT` (
    `RECEIPT_ID` VARCHAR(50) NOT NULL COMMENT '입고 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT '입고 Lot 번호',
    `QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '입고 수량',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `RECEIPT_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '입고 일시',
    `WAREHOUSE_CODE` VARCHAR(50) NOT NULL COMMENT '입고 창고 코드',
    `LOCATION_CODE` VARCHAR(50) NULL COMMENT '창고 위치 코드',
    `RECEIPT_TYPE` VARCHAR(50) NULL COMMENT '입고 유형 (구매, 반품 등)',
    `VENDOR_ID` VARCHAR(50) NULL COMMENT '업체 ID (구매처)',
    `EXPIRATION_DATE` DATE NULL COMMENT '유효 기간 (선택사항)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`RECEIPT_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`WAREHOUSE_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 창고 코드 참조
    FOREIGN KEY (`LOCATION_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 창고 위치 코드 참조
    FOREIGN KEY (`RECEIPT_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 입고 유형 참조
    FOREIGN KEY (`VENDOR_ID`) REFERENCES `TB_VENDOR` (`VENDOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='자재 입고';

-- 40. TB_CUSTOMER (고객 마스터)
CREATE TABLE `TB_CUSTOMER` (
    `CUSTOMER_ID` VARCHAR(50) NOT NULL COMMENT '고객 ID',
    `CUSTOMER_NAME` VARCHAR(200) NOT NULL COMMENT '고객명',
    `CONTACT_PERSON` VARCHAR(100) NULL COMMENT '담당자',
    `PHONE_NUMBER` VARCHAR(20) NULL COMMENT '연락처',
    `ADDRESS` VARCHAR(255) NULL COMMENT '주소',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='고객 마스터';

-- 41. TB_FG_INVENTORY (완제품 재고)
CREATE TABLE `TB_FG_INVENTORY` (
    `INVENTORY_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '재고 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT 'Lot 번호',
    `SERIAL_NO` VARCHAR(100) NULL COMMENT 'Serial 번호',
    `WAREHOUSE_CODE` VARCHAR(50) NOT NULL COMMENT '창고 코드',
    `LOCATION_CODE` VARCHAR(50) NULL COMMENT '위치 코드',
    `CURRENT_QTY` DECIMAL(10,4) NOT NULL COMMENT '현재 재고 수량 (Serial은 보통 1)',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `LAST_UPDATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 업데이트 일시',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`INVENTORY_ID`),
    UNIQUE KEY `UK_ITEM_LOT_SERIAL_WAREHOUSE_LOCATION` (`ITEM_ID`, `LOT_NO`, `SERIAL_NO`, `WAREHOUSE_CODE`, `LOCATION_CODE`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`WAREHOUSE_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`), -- 공통 코드의 창고 코드 참조
    FOREIGN KEY (`LOCATION_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 위치 코드 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='완제품 재고';

-- 42. TB_SHIPMENT_ORDER (출하 지시)
CREATE TABLE `TB_SHIPMENT_ORDER` (
    `SHIPMENT_ORDER_ID` VARCHAR(50) NOT NULL COMMENT '출하 지시 ID',
    `CUSTOMER_ID` VARCHAR(50) NOT NULL COMMENT '고객 ID',
    `ORDER_DATE` DATE NOT NULL COMMENT '지시 일자',
    `REQUIRED_DELIVERY_DATE` DATE NOT NULL COMMENT '요청 납기일',
    `ORDER_STATUS` VARCHAR(20) NOT NULL COMMENT '지시 상태 (예: 발행, 진행중, 완료, 취소)',
    `REMARKS` VARCHAR(500) NULL COMMENT '비고',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`SHIPMENT_ORDER_ID`),
    FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `TB_CUSTOMER` (`CUSTOMER_ID`),
    FOREIGN KEY (`ORDER_STATUS`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 출하 지시 상태 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='출하 지시';

-- 43. TB_SHIPMENT_HISTORY (출하 이력)
CREATE TABLE `TB_SHIPMENT_HISTORY` (
    `SHIPMENT_HISTORY_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '출하 이력 ID',
    `SHIPMENT_ORDER_ID` VARCHAR(50) NOT NULL COMMENT '관련 출하 지시 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT '출하 Lot 번호',
    `SERIAL_NO` VARCHAR(100) NULL COMMENT '출하 Serial 번호',
    `SHIPPED_QTY` DECIMAL(10,4) NOT NULL COMMENT '출하 수량',
    `SHIPPED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '출하 일시',
    `SHIPPED_BY_USER_ID` VARCHAR(50) NOT NULL COMMENT '출하 담당자 ID',
    `CARRIER_INFO` VARCHAR(255) NULL COMMENT '운송 정보',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`SHIPMENT_HISTORY_ID`),
    FOREIGN KEY (`SHIPMENT_ORDER_ID`) REFERENCES `TB_SHIPMENT_ORDER` (`SHIPMENT_ORDER_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`SHIPPED_BY_USER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='출하 이력';

-- 44. TB_ANALYSIS_PLAN_VS_ACTUAL (생산 계획 vs 실적 분석)
CREATE TABLE `TB_ANALYSIS_PLAN_VS_ACTUAL` (
    `ANALYSIS_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '분석 ID',
    `PLAN_ID` VARCHAR(50) NOT NULL COMMENT '생산 계획 ID',
    `ACTUAL_PERFORMANCE_ID` BIGINT NULL COMMENT '실제 생산 실적 ID',
    `ANALYSIS_DATE` DATE NOT NULL COMMENT '분석 일자',
    `PLAN_QTY` DECIMAL(10,4) NOT NULL COMMENT '계획 수량',
    `ACTUAL_QTY` DECIMAL(10,4) NULL COMMENT '실제 생산 수량',
    `ACHIEVEMENT_RATE` DECIMAL(5,2) NULL COMMENT '달성율 (%)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ANALYSIS_ID`),
    FOREIGN KEY (`PLAN_ID`) REFERENCES `TB_PRODUCTION_PLAN` (`PLAN_ID`),
    FOREIGN KEY (`ACTUAL_PERFORMANCE_ID`) REFERENCES `TB_PRODUCTION_PERFORMANCE` (`PERFORMANCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='생산 계획 vs 실적 분석';

-- 45. TB_ANALYSIS_PRODUCTIVITY (생산성 분석)
CREATE TABLE `TB_ANALYSIS_PRODUCTIVITY` (
    `ANALYSIS_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '분석 ID',
    `ANALYSIS_DATE` DATE NOT NULL COMMENT '분석 일자',
    `LINE_ID` VARCHAR(50) NOT NULL COMMENT '라인 ID',
    `WORKPLACE_ID` VARCHAR(50) NOT NULL COMMENT '작업장 ID',
    `TOTAL_PRODUCTION_QTY` DECIMAL(10,4) NOT NULL COMMENT '총 생산 수량',
    `TOTAL_RUN_TIME` DECIMAL(10,2) NOT NULL COMMENT '총 가동 시간 (분)',
    `PRODUCTIVITY` DECIMAL(10,4) NOT NULL COMMENT '생산성 (단위/시간)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ANALYSIS_ID`),
    UNIQUE KEY `UK_ANALYSIS_DATE_LINE_WORKPLACE` (`ANALYSIS_DATE`, `LINE_ID`, `WORKPLACE_ID`),
    FOREIGN KEY (`LINE_ID`) REFERENCES `TB_LINE` (`LINE_ID`),
    FOREIGN KEY (`WORKPLACE_ID`) REFERENCES `TB_WORKPLACE` (`WORKPLACE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='생산성 분석';

-- 46. TB_ANALYSIS_LEAD_TIME (리드 타임 분석)
CREATE TABLE `TB_ANALYSIS_LEAD_TIME` (
    `ANALYSIS_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '분석 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOT_NO` VARCHAR(100) NOT NULL COMMENT 'Lot 번호',
    `START_TIME` DATETIME NOT NULL COMMENT '시작 시간',
    `END_TIME` DATETIME NOT NULL COMMENT '종료 시간',
    `LEAD_TIME_HOURS` DECIMAL(10,2) NOT NULL COMMENT '리드 타임 (시간)',
    `LEAD_TIME_TYPE` VARCHAR(50) NOT NULL COMMENT '리드 타임 유형 (생산, 공정, 출하 등)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ANALYSIS_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`LEAD_TIME_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 리드 타임 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='리드 타임 분석';

-- 47. TB_ANALYSIS_DEFECT (불량률 분석)
CREATE TABLE `TB_ANALYSIS_DEFECT` (
    `ANALYSIS_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '분석 ID',
    `ANALYSIS_DATE` DATE NOT NULL COMMENT '분석 일자',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `TOTAL_PRODUCTION_QTY` DECIMAL(10,4) NOT NULL COMMENT '총 생산 수량',
    `TOTAL_DEFECT_QTY` DECIMAL(10,4) NOT NULL COMMENT '총 불량 수량',
    `DEFECT_RATE` DECIMAL(5,2) NOT NULL COMMENT '불량률 (%)',
    `DEFECT_CODE` VARCHAR(50) NULL COMMENT '주요 불량 유형 코드',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ANALYSIS_ID`),
    UNIQUE KEY `UK_ANALYSIS_DATE_ITEM` (`ANALYSIS_DATE`, `ITEM_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`DEFECT_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 불량 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='불량률 분석';

-- 48. TB_ANALYSIS_DOWNTIME (비가동 분석)
CREATE TABLE `TB_ANALYSIS_DOWNTIME` (
    `ANALYSIS_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '분석 ID',
    `ANALYSIS_DATE` DATE NOT NULL COMMENT '분석 일자',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `TOTAL_DOWNTIME_HOURS` DECIMAL(10,2) NOT NULL COMMENT '총 비가동 시간 (시간)',
    `DOWNTIME_COUNT` INT NOT NULL COMMENT '비가동 발생 건수',
    `MAIN_DOWNTIME_CODE` VARCHAR(50) NULL COMMENT '주요 비가동 사유 코드',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ANALYSIS_ID`),
    UNIQUE KEY `UK_ANALYSIS_DATE_EQUIP` (`ANALYSIS_DATE`, `EQUIP_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`),
    FOREIGN KEY (`MAIN_DOWNTIME_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 비가동 사유 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='비가동 분석';