-- MySQL Database DDL Script for MES_DB (수정 및 최적화 버전)

-- 데이터베이스 생성 (선택 사항, 이미 존재하면 생략)
CREATE DATABASE IF NOT EXISTS `MES_DB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `MES_DB`;

-- 1. TB_COMMON_CODE_GROUP (공통 코드 그룹)
CREATE TABLE `TB_COMMON_CODE_GROUP` (
    `GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '공통 코드 그룹 코드',
    `GROUP_NAME` VARCHAR(100) NOT NULL COMMENT '공통 코드 그룹명',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`GROUP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공통 코드 그룹';

-- 2. TB_COMMON_CODE (공통 코드)
CREATE TABLE `TB_COMMON_CODE` (
    `CODE_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '코드 ID',
    `GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '공통 코드 그룹 코드',
    `CODE_VALUE` VARCHAR(50) NOT NULL COMMENT '코드 값',
    `CODE_NAME` VARCHAR(100) NOT NULL COMMENT '코드명',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `SORT_ORDER` INT NULL DEFAULT 0 COMMENT '정렬 순서',
    `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y/N)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`CODE_ID`),
    UNIQUE KEY `UK_GROUP_CODE_VALUE` (`GROUP_CODE`, `CODE_VALUE`),
    FOREIGN KEY (`GROUP_CODE`) REFERENCES `TB_COMMON_CODE_GROUP` (`GROUP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공통 코드';

-- 3. TB_USER (사용자 정보)
CREATE TABLE `TB_USER` (
    `USER_ID` VARCHAR(50) NOT NULL COMMENT '사용자 ID',
    `PASSWORD` VARCHAR(255) NOT NULL COMMENT '비밀번호',
    `USER_NAME` VARCHAR(100) NOT NULL COMMENT '사용자명',
    `EMAIL` VARCHAR(100) NULL COMMENT '이메일',
    `PHONE_NUMBER` VARCHAR(20) NULL COMMENT '연락처',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 정보';

-- 4. TB_ROLE (역할/권한)
CREATE TABLE `TB_ROLE` (
    `ROLE_ID` VARCHAR(50) NOT NULL COMMENT '역할 ID',
    `ROLE_NAME` VARCHAR(100) NOT NULL COMMENT '역할명',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='역할/권한';

-- 5. TB_ORGANIZATION (조직 정보)
CREATE TABLE `TB_ORGANIZATION` (
    `ORG_ID` VARCHAR(50) NOT NULL COMMENT '조직 ID',
    `ORG_NAME` VARCHAR(100) NOT NULL COMMENT '조직명',
    `PARENT_ORG_ID` VARCHAR(50) NULL COMMENT '상위 조직 ID',
    `ORG_TYPE` VARCHAR(50) NULL COMMENT '조직 유형 (예: 부서, 팀, 공장 등)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ORG_ID`),
    CONSTRAINT `FK_ORG_PARENT` FOREIGN KEY (`PARENT_ORG_ID`) REFERENCES `TB_ORGANIZATION` (`ORG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='조직 정보';

-- 6. TB_SYSTEM_MENU (시스템 메뉴)
CREATE TABLE `TB_SYSTEM_MENU` (
    `MENU_ID` VARCHAR(50) NOT NULL COMMENT '메뉴 ID',
    `MENU_NAME` VARCHAR(100) NOT NULL COMMENT '메뉴명',
    `PARENT_MENU_ID` VARCHAR(50) NULL COMMENT '상위 메뉴 ID',
    `MENU_URL` VARCHAR(255) NULL COMMENT '메뉴 URL',
    `MENU_ORDER` INT NULL DEFAULT 0 COMMENT '메뉴 순서',
    `ICON` VARCHAR(50) NULL COMMENT '아이콘',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`MENU_ID`),
    CONSTRAINT `FK_MENU_PARENT` FOREIGN KEY (`PARENT_MENU_ID`) REFERENCES `TB_SYSTEM_MENU` (`MENU_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='시스템 메뉴';

-- 7. TB_MENU_ROLE_MAPPING (메뉴 역할 매핑)
CREATE TABLE `TB_MENU_ROLE_MAPPING` (
    `MAPPING_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '매핑 ID',
    `MENU_ID` VARCHAR(50) NOT NULL COMMENT '메뉴 ID',
    `ROLE_ID` VARCHAR(50) NOT NULL COMMENT '역할 ID',
    `CAN_VIEW` TINYINT NOT NULL DEFAULT 1 COMMENT '조회 가능 여부',
    `CAN_EDIT` TINYINT NOT NULL DEFAULT 0 COMMENT '편집 가능 여부',
    `CAN_DELETE` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 가능 여부',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`MAPPING_ID`),
    UNIQUE KEY `UK_MENU_ROLE` (`MENU_ID`, `ROLE_ID`),
    CONSTRAINT `FK_MAPPING_MENU` FOREIGN KEY (`MENU_ID`) REFERENCES `TB_SYSTEM_MENU` (`MENU_ID`),
    CONSTRAINT `FK_MAPPING_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `TB_ROLE` (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='메뉴 역할 매핑';

-- 8. TB_ITEM (품목 마스터)
CREATE TABLE `TB_ITEM` (
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `ITEM_NAME` VARCHAR(200) NOT NULL COMMENT '품목명',
    `ITEM_TYPE` VARCHAR(50) NOT NULL COMMENT '품목 유형 (제품, 반제품, 원자재, 부자재)',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '기본 단위',
    `SPECIFICATION` VARCHAR(255) NULL COMMENT '규격',
    `DESCRIPTION` VARCHAR(500) NULL COMMENT '설명',
    `SAFETY_STOCK_QTY` DECIMAL(10,4) NULL DEFAULT 0 COMMENT '안전 재고 수량',
    `LEAD_TIME_DAYS` INT NULL DEFAULT 0 COMMENT '리드 타임 (일)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='품목 마스터';

-- 9. TB_MES_BOM (BOM 마스터)
CREATE TABLE `TB_MES_BOM` (
    `BOM_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT 'BOM ID',
    `PARENT_ITEM_ID` VARCHAR(50) NOT NULL COMMENT '상위 품목 ID',
    `CHILD_ITEM_ID` VARCHAR(50) NOT NULL COMMENT '하위 품목 ID',
    `QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '소요 수량',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `START_DATE` DATE NULL COMMENT '유효 시작일',
    `END_DATE` DATE NULL COMMENT '유효 종료일',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`BOM_ID`),
    UNIQUE KEY `UK_PARENT_CHILD` (`PARENT_ITEM_ID`, `CHILD_ITEM_ID`),
    CONSTRAINT `FK_BOM_PARENT_ITEM` FOREIGN KEY (`PARENT_ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    CONSTRAINT `FK_BOM_CHILD_ITEM` FOREIGN KEY (`CHILD_ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='BOM 마스터';

-- 10. TB_COMPONENT_PRODUCT_MAPPING (원자재-제품 매핑)
CREATE TABLE `TB_COMPONENT_PRODUCT_MAPPING` (
    `MAPPING_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '매핑 ID',
    `COMPONENT_ITEM_ID` VARCHAR(50) NOT NULL COMMENT '원자재 품목 ID',
    `PRODUCT_ITEM_ID` VARCHAR(50) NOT NULL COMMENT '제품 품목 ID',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`MAPPING_ID`),
    UNIQUE KEY `UK_COMPONENT_PRODUCT` (`COMPONENT_ITEM_ID`, `PRODUCT_ITEM_ID`),
    CONSTRAINT `FK_COMP_PROD_COMPONENT` FOREIGN KEY (`COMPONENT_ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    CONSTRAINT `FK_COMP_PROD_PRODUCT` FOREIGN KEY (`PRODUCT_ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='원자재-제품 매핑';

-- 11. TB_ROUTE (공정 라우팅)
CREATE TABLE `TB_ROUTE` (
    `ROUTE_ID` VARCHAR(50) NOT NULL COMMENT '라우팅 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `ROUTE_NAME` VARCHAR(100) NOT NULL COMMENT '라우팅명',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ROUTE_ID`),
    UNIQUE KEY `UK_ITEM_ID` (`ITEM_ID`),
    CONSTRAINT `FK_ROUTE_ITEM` FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공정 라우팅';

-- 12. TB_WORKPLACE (작업장 마스터)
CREATE TABLE `TB_WORKPLACE` (
    `WORKPLACE_ID` VARCHAR(50) NOT NULL COMMENT '작업장 ID',
    `WORKPLACE_NAME` VARCHAR(100) NOT NULL COMMENT '작업장명',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `LOCATION` VARCHAR(100) NULL COMMENT '위치',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`WORKPLACE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='작업장 마스터';

-- 13. TB_ROUTE_OPERATION (라우팅 공정)
CREATE TABLE `TB_ROUTE_OPERATION` (
    `OPERATION_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '공정 ID',
    `ROUTE_ID` VARCHAR(50) NOT NULL COMMENT '라우팅 ID',
    `OPERATION_GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '공정 공통 코드 그룹',
    `OPERATION_CODE` VARCHAR(50) NOT NULL COMMENT '공정 코드',
    `OPERATION_NAME` VARCHAR(100) NOT NULL COMMENT '공정명',
    `WORKPLACE_ID` VARCHAR(50) NOT NULL COMMENT '작업장 ID',
    `SEQUENCE` INT NOT NULL COMMENT '공정 순서',
    `STANDARD_TIME_PER_UNIT` DECIMAL(10,4) NULL COMMENT '단위당 표준 시간',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`OPERATION_ID`),
    UNIQUE KEY `UK_ROUTE_SEQUENCE` (`ROUTE_ID`, `SEQUENCE`),
    CONSTRAINT `FK_ROUT_OPER_ROUTE` FOREIGN KEY (`ROUTE_ID`) REFERENCES `TB_ROUTE` (`ROUTE_ID`),
    CONSTRAINT `FK_ROUT_OPER_WORKPLACE` FOREIGN KEY (`WORKPLACE_ID`) REFERENCES `TB_WORKPLACE` (`WORKPLACE_ID`),
    CONSTRAINT `FK_ROUT_OPER_COMMON_CODE` FOREIGN KEY (`OPERATION_GROUP_CODE`, `OPERATION_CODE`) REFERENCES `TB_COMMON_CODE` (`GROUP_CODE`, `CODE_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='라우팅 공정';

-- 14. TB_LINE (생산 라인)
CREATE TABLE `TB_LINE` (
    `LINE_ID` VARCHAR(50) NOT NULL COMMENT '라인 ID',
    `LINE_NAME` VARCHAR(100) NOT NULL COMMENT '라인명',
    `WORKPLACE_ID` VARCHAR(50) NOT NULL COMMENT '속한 작업장 ID',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`LINE_ID`),
    CONSTRAINT `FK_LINE_WORKPLACE` FOREIGN KEY (`WORKPLACE_ID`) REFERENCES `TB_WORKPLACE` (`WORKPLACE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='생산 라인';

-- 15. TB_EQUIPMENT (설비 마스터)
CREATE TABLE `TB_EQUIPMENT` (
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `EQUIP_NAME` VARCHAR(100) NOT NULL COMMENT '설비명',
    `LINE_ID` VARCHAR(50) NOT NULL COMMENT '속한 라인 ID',
    `EQUIP_GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '설비 공통 코드 그룹',
    `EQUIP_TYPE` VARCHAR(50) NULL COMMENT '설비 유형',
    `MODEL_NO` VARCHAR(100) NULL COMMENT '모델 번호',
    `SERIAL_NO` VARCHAR(100) NULL COMMENT '시리얼 번호',
    `INSTALL_DATE` DATE NULL COMMENT '설치 일자',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`EQUIP_ID`),
    CONSTRAINT `FK_EQUIP_LINE` FOREIGN KEY (`LINE_ID`) REFERENCES `TB_LINE` (`LINE_ID`),
    CONSTRAINT `FK_EQUIP_COMMON_CODE` FOREIGN KEY (`EQUIP_GROUP_CODE`, `EQUIP_TYPE`) REFERENCES `TB_COMMON_CODE` (`GROUP_CODE`, `CODE_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='설비 마스터';

-- 16. TB_EQUIPMENT_SENSOR_DATA (설비 센서 데이터)
CREATE TABLE `TB_EQUIPMENT_SENSOR_DATA` (
    `DATA_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '데이터 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `SENSOR_TYPE` VARCHAR(50) NOT NULL COMMENT '센서 유형 (온도, 압력, 진동 등)',
    `SENSOR_VALUE` DECIMAL(18,4) NOT NULL COMMENT '센서 값',
    `UNIT` VARCHAR(10) NULL COMMENT '단위',
    `COLLECTION_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '데이터 수집 시간',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`DATA_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='설비 센서 데이터';

-- 17. TB_WORK_ORDER (작업 지시)
CREATE TABLE `TB_WORK_ORDER` (
    `WORK_ORDER_ID` VARCHAR(50) NOT NULL COMMENT '작업 지시 ID',
    `PRODUCTION_PLAN_ID` VARCHAR(50) NULL COMMENT '생산 계획 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '지시 수량',
    `WORK_ORDER_STATUS` VARCHAR(50) NOT NULL COMMENT '작업 지시 상태 (계획, 대기, 진행, 완료, 취소)',
    `START_DATE` DATE NOT NULL COMMENT '시작 예정일',
    `DUE_DATE` DATE NOT NULL COMMENT '완료 예정일',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`WORK_ORDER_ID`),
    FOREIGN KEY (`PRODUCTION_PLAN_ID`) REFERENCES `TB_PRODUCTION_PLAN` (`PLAN_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    CONSTRAINT `FK_WO_STATUS_COMMON_CODE` FOREIGN KEY (`WORK_ORDER_STATUS`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 작업 지시 상태 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='작업 지시';

-- 18. TB_PRODUCTION_ORDER (생산 지시)
CREATE TABLE `TB_PRODUCTION_ORDER` (
    `PRODUCTION_ORDER_ID` VARCHAR(50) NOT NULL COMMENT '생산 지시 ID',
    `WORK_ORDER_ID` VARCHAR(50) NOT NULL COMMENT '작업 지시 ID',
    `ROUTE_ID` VARCHAR(50) NOT NULL COMMENT '라우팅 ID',
    `ORDER_QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '생산 지시 수량',
    `ORDER_STATUS` VARCHAR(50) NOT NULL COMMENT '생산 지시 상태',
    `START_DATE` DATETIME NULL COMMENT '실제 시작 일시',
    `END_DATE` DATETIME NULL COMMENT '실제 완료 일시',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`PRODUCTION_ORDER_ID`),
    FOREIGN KEY (`WORK_ORDER_ID`) REFERENCES `TB_WORK_ORDER` (`WORK_ORDER_ID`),
    FOREIGN KEY (`ROUTE_ID`) REFERENCES `TB_ROUTE` (`ROUTE_ID`),
    CONSTRAINT `FK_PO_STATUS_COMMON_CODE` FOREIGN KEY (`ORDER_STATUS`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 생산 지시 상태 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='생산 지시';

-- 19. TB_PRODUCTION_PLAN (생산 계획)
CREATE TABLE `TB_PRODUCTION_PLAN` (
    `PLAN_ID` VARCHAR(50) NOT NULL COMMENT '계획 ID',
    `PLAN_NAME` VARCHAR(100) NOT NULL COMMENT '계획명',
    `PLAN_DATE` DATE NOT NULL COMMENT '계획 일자',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `PLAN_QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '계획 수량',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`PLAN_ID`),
    UNIQUE KEY `UK_PLAN_DATE_ITEM` (`PLAN_DATE`, `ITEM_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='생산 계획';

-- 20. TB_PRODUCTION_PERFORMANCE (생산 실적)
CREATE TABLE `TB_PRODUCTION_PERFORMANCE` (
    `PERF_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '실적 ID',
    `PRODUCTION_ORDER_ID` VARCHAR(50) NOT NULL COMMENT '생산 지시 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `PERF_DATE` DATE NOT NULL COMMENT '실적 일자',
    `PERF_QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '생산 수량',
    `GOOD_QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '양품 수량',
    `DEFECT_QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '불량 수량',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOTETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`PERF_ID`),
    FOREIGN KEY (`PRODUCTION_ORDER_ID`) REFERENCES `TB_PRODUCTION_ORDER` (`PRODUCTION_ORDER_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='생산 실적';

-- 21. TB_PRODUCTION_HISTORY (생산 이력)
CREATE TABLE `TB_PRODUCTION_HISTORY` (
    `HISTORY_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '이력 ID',
    `PRODUCTION_ORDER_ID` VARCHAR(50) NOT NULL COMMENT '생산 지시 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `OPERATION_CODE` VARCHAR(50) NOT NULL COMMENT '공정 코드',
    `WORK_START_TIME` DATETIME NOT NULL COMMENT '작업 시작 시간',
    `WORK_END_TIME` DATETIME NULL COMMENT '작업 종료 시간',
    `WORK_USER_ID` VARCHAR(50) NULL COMMENT '작업자 ID',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`HISTORY_ID`),
    FOREIGN KEY (`PRODUCTION_ORDER_ID`) REFERENCES `TB_PRODUCTION_ORDER` (`PRODUCTION_ORDER_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`),
    FOREIGN KEY (`WORK_USER_ID`) REFERENCES `TB_USER` (`USER_ID`),
    CONSTRAINT `FK_PROD_HIST_OP_COMMON_CODE` FOREIGN KEY (`OPERATION_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 공정 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='생산 이력';

-- 22. TB_DEFECT_ITEM (불량 품목)
CREATE TABLE `TB_DEFECT_ITEM` (
    `DEFECT_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '불량 ID',
    `PERF_ID` BIGINT NOT NULL COMMENT '생산 실적 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '불량 품목 ID',
    `DEFECT_GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '불량 공통 코드 그룹',
    `DEFECT_CODE` VARCHAR(50) NOT NULL COMMENT '불량 코드',
    `DEFECT_QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '불량 수량',
    `DEFECT_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '불량 발생 일시',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`DEFECT_ID`),
    FOREIGN KEY (`PERF_ID`) REFERENCES `TB_PRODUCTION_PERFORMANCE` (`PERF_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    CONSTRAINT `FK_DEFECT_COMMON_CODE` FOREIGN KEY (`DEFECT_GROUP_CODE`, `DEFECT_CODE`) REFERENCES `TB_COMMON_CODE` (`GROUP_CODE`, `CODE_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='불량 품목';

-- 23. TB_INVENTORY (재고 정보)
CREATE TABLE `TB_INVENTORY` (
    `INVENTORY_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '재고 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOCATION_CODE` VARCHAR(50) NOT NULL COMMENT '창고 위치 코드',
    `LOT_NUMBER` VARCHAR(50) NULL COMMENT 'LOT 번호',
    `QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '재고 수량',
    `UNIT` VARCHAR(10) NOT NULL COMMENT '단위',
    `EXPIRY_DATE` DATE NULL COMMENT '유효 기간',
    `LAST_UPDATE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 업데이트 일시',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`INVENTORY_ID`),
    UNIQUE KEY `UK_ITEM_LOT_LOCATION` (`ITEM_ID`, `LOT_NUMBER`, `LOCATION_CODE`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='재고 정보';

-- 24. TB_STOCK_MOVEMENT (재고 이동 이력)
CREATE TABLE `TB_STOCK_MOVEMENT` (
    `MOVEMENT_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '이동 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `LOT_NUMBER` VARCHAR(50) NULL COMMENT 'LOT 번호',
    `FROM_LOCATION_CODE` VARCHAR(50) NULL COMMENT '출발 창고 위치',
    `TO_LOCATION_CODE` VARCHAR(50) NOT NULL COMMENT '도착 창고 위치',
    `MOVEMENT_QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '이동 수량',
    `MOVEMENT_TYPE` VARCHAR(50) NOT NULL COMMENT '이동 유형 (입고, 출고, 이동)',
    `MOVEMENT_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '이동 일시',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`MOVEMENT_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    CONSTRAINT `FK_STOCK_MOVE_TYPE_COMMON_CODE` FOREIGN KEY (`MOVEMENT_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 재고 이동 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='재고 이동 이력';

-- 25. TB_WAREHOUSE (창고 마스터)
CREATE TABLE `TB_WAREHOUSE` (
    `WAREHOUSE_ID` VARCHAR(50) NOT NULL COMMENT '창고 ID',
    `WAREHOUSE_NAME` VARCHAR(100) NOT NULL COMMENT '창고명',
    `LOCATION` VARCHAR(255) NULL COMMENT '위치',
    `DESCRIPTION` VARCHAR(255) NULL COMMENT '설명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`WAREHOUSE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='창고 마스터';

-- 26. TB_LOT_MASTER (LOT 마스터)
CREATE TABLE `TB_LOT_MASTER` (
    `LOT_NUMBER` VARCHAR(50) NOT NULL COMMENT 'LOT 번호',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `PRODUCTION_DATE` DATE NOT NULL COMMENT '생산 일자',
    `EXPIRY_DATE` DATE NULL COMMENT '유효 기간',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`LOT_NUMBER`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='LOT 마스터';

-- 27. TB_INSPECTION_PLAN (검사 계획)
CREATE TABLE `TB_INSPECTION_PLAN` (
    `INSPECTION_PLAN_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '검사 계획 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `INSPECTION_TYPE` VARCHAR(50) NOT NULL COMMENT '검사 유형 (예: 수입, 공정, 출하)',
    `SAMPLING_RATE` DECIMAL(5,2) NOT NULL DEFAULT 0 COMMENT '샘플링 비율 (%)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`INSPECTION_PLAN_ID`),
    UNIQUE KEY `UK_ITEM_INSP_TYPE` (`ITEM_ID`, `INSPECTION_TYPE`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='검사 계획';

-- 28. TB_INSPECTION_RESULT (검사 결과)
CREATE TABLE `TB_INSPECTION_RESULT` (
    `INSPECTION_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '검사 ID',
    `INSPECTION_PLAN_ID` BIGINT NOT NULL COMMENT '검사 계획 ID',
    `LOT_NUMBER` VARCHAR(50) NOT NULL COMMENT 'LOT 번호',
    `INSPECTION_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '검사 일시',
    `INSPECTION_RESULT` VARCHAR(50) NOT NULL COMMENT '검사 결과 (합격, 불합격)',
    `INSPECTOR_ID` VARCHAR(50) NOT NULL COMMENT '검사자 ID',
    `NOTES` VARCHAR(500) NULL COMMENT '비고',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`INSPECTION_ID`),
    UNIQUE KEY `UK_LOT_INSP` (`LOT_NUMBER`, `INSPECTION_PLAN_ID`),
    FOREIGN KEY (`INSPECTION_PLAN_ID`) REFERENCES `TB_INSPECTION_PLAN` (`INSPECTION_PLAN_ID`),
    FOREIGN KEY (`INSPECTOR_ID`) REFERENCES `TB_USER` (`USER_ID`),
    CONSTRAINT `FK_INSP_RES_COMMON_CODE` FOREIGN KEY (`INSPECTION_RESULT`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 검사 결과 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='검사 결과';

-- 29. TB_INSPECTION_DEFECT (검사 불량)
CREATE TABLE `TB_INSPECTION_DEFECT` (
    `INSPECTION_DEFECT_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '검사 불량 ID',
    `INSPECTION_ID` BIGINT NOT NULL COMMENT '검사 ID',
    `DEFECT_GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '불량 공통 코드 그룹',
    `DEFECT_CODE` VARCHAR(50) NOT NULL COMMENT '불량 코드',
    `DEFECT_QUANTITY` DECIMAL(10,4) NOT NULL COMMENT '불량 수량',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`INSPECTION_DEFECT_ID`),
    FOREIGN KEY (`INSPECTION_ID`) REFERENCES `TB_INSPECTION_RESULT` (`INSPECTION_ID`),
    CONSTRAINT `FK_INSP_DEFECT_COMMON_CODE` FOREIGN KEY (`DEFECT_GROUP_CODE`, `DEFECT_CODE`) REFERENCES `TB_COMMON_CODE` (`GROUP_CODE`, `CODE_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='검사 불량';

-- 30. TB_QUALITY_CHECKLIST (품질 점검표)
CREATE TABLE `TB_QUALITY_CHECKLIST` (
    `CHECKLIST_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '점검표 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `CHECKLIST_NAME` VARCHAR(100) NOT NULL COMMENT '점검표명',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`CHECKLIST_ID`),
    UNIQUE KEY `UK_CHECKLIST_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='품질 점검표';

-- 31. TB_QUALITY_CHECKLIST_ITEM (품질 점검 항목)
CREATE TABLE `TB_QUALITY_CHECKLIST_ITEM` (
    `CHECKLIST_ITEM_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '점검 항목 ID',
    `CHECKLIST_ID` BIGINT NOT NULL COMMENT '점검표 ID',
    `CHECK_ITEM_NAME` VARCHAR(100) NOT NULL COMMENT '점검 항목명',
    `CHECK_SPECIFICATION` VARCHAR(255) NULL COMMENT '점검 기준',
    `CHECK_TYPE` VARCHAR(50) NOT NULL COMMENT '점검 유형 (측정, 육안 등)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`CHECKLIST_ITEM_ID`),
    FOREIGN KEY (`CHECKLIST_ID`) REFERENCES `TB_QUALITY_CHECKLIST` (`CHECKLIST_ID`),
    CONSTRAINT `FK_CHK_ITEM_TYPE_COMMON_CODE` FOREIGN KEY (`CHECK_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 점검 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='품질 점검 항목';

-- 32. TB_QUALITY_CHECK_RESULT (품질 점검 결과)
CREATE TABLE `TB_QUALITY_CHECK_RESULT` (
    `RESULT_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '결과 ID',
    `CHECKLIST_ITEM_ID` BIGINT NOT NULL COMMENT '점검 항목 ID',
    `INSPECTION_ID` BIGINT NOT NULL COMMENT '검사 ID',
    `CHECK_RESULT_VALUE` VARCHAR(255) NULL COMMENT '점검 결과 값',
    `CHECK_RESULT_CODE` VARCHAR(50) NOT NULL COMMENT '점검 결과 코드 (정상, 불량, 측정값)',
    `INSPECTOR_ID` VARCHAR(50) NOT NULL COMMENT '점검자 ID',
    `CHECK_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '점검 일시',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`RESULT_ID`),
    UNIQUE KEY `UK_CHKLIST_INSP` (`CHECKLIST_ITEM_ID`, `INSPECTION_ID`),
    FOREIGN KEY (`CHECKLIST_ITEM_ID`) REFERENCES `TB_QUALITY_CHECKLIST_ITEM` (`CHECKLIST_ITEM_ID`),
    FOREIGN KEY (`INSPECTION_ID`) REFERENCES `TB_INSPECTION_RESULT` (`INSPECTION_ID`),
    FOREIGN KEY (`INSPECTOR_ID`) REFERENCES `TB_USER` (`USER_ID`),
    CONSTRAINT `FK_CHK_RES_CODE_COMMON_CODE` FOREIGN KEY (`CHECK_RESULT_CODE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 점검 결과 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='품질 점검 결과';

-- 33. TB_EQUIPMENT_MAINTENANCE (설비 보전)
CREATE TABLE `TB_EQUIPMENT_MAINTENANCE` (
    `MAINTENANCE_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '보전 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `MAINTENANCE_TYPE` VARCHAR(50) NOT NULL COMMENT '보전 유형 (예: 예방, 사후, 예측)',
    `MAINTENANCE_DATE` DATE NOT NULL COMMENT '보전 일자',
    `MAINTENANCE_DESCRIPTION` VARCHAR(500) NULL COMMENT '보전 내용',
    `MAINTENANCE_COST` DECIMAL(10,2) NULL DEFAULT 0 COMMENT '보전 비용',
    `MAINTENANCE_USER_ID` VARCHAR(50) NOT NULL COMMENT '보전 담당자 ID',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`MAINTENANCE_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`),
    FOREIGN KEY (`MAINTENANCE_USER_ID`) REFERENCES `TB_USER` (`USER_ID`),
    CONSTRAINT `FK_MAINT_TYPE_COMMON_CODE` FOREIGN KEY (`MAINTENANCE_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 보전 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='설비 보전';

-- 34. TB_EQUIPMENT_DOWNTIME (설비 비가동)
CREATE TABLE `TB_EQUIPMENT_DOWNTIME` (
    `DOWNTIME_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '비가동 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `DOWNTIME_GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '비가동 공통 코드 그룹',
    `DOWNTIME_CODE` VARCHAR(50) NOT NULL COMMENT '비가동 사유 코드',
    `START_TIME` DATETIME NOT NULL COMMENT '비가동 시작 시간',
    `END_TIME` DATETIME NULL COMMENT '비가동 종료 시간',
    `DESCRIPTION` VARCHAR(500) NULL COMMENT '비고',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`DOWNTIME_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`),
    CONSTRAINT `FK_DOWNTIME_COMMON_CODE` FOREIGN KEY (`DOWNTIME_GROUP_CODE`, `DOWNTIME_CODE`) REFERENCES `TB_COMMON_CODE` (`GROUP_CODE`, `CODE_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='설비 비가동';

-- 35. TB_SHIFT_PLAN (교대 계획)
CREATE TABLE `TB_SHIFT_PLAN` (
    `PLAN_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '계획 ID',
    `PLAN_DATE` DATE NOT NULL COMMENT '계획 일자',
    `SHIFT_GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '교대조 공통 코드 그룹',
    `SHIFT_CODE` VARCHAR(50) NOT NULL COMMENT '교대조 코드',
    `LINE_ID` VARCHAR(50) NOT NULL COMMENT '생산 라인 ID',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`PLAN_ID`),
    UNIQUE KEY `UK_PLAN_DATE_SHIFT_LINE` (`PLAN_DATE`, `SHIFT_GROUP_CODE`, `SHIFT_CODE`, `LINE_ID`),
    FOREIGN KEY (`LINE_ID`) REFERENCES `TB_LINE` (`LINE_ID`),
    CONSTRAINT `FK_SHIFT_PLAN_COMMON_CODE` FOREIGN KEY (`SHIFT_GROUP_CODE`, `SHIFT_CODE`) REFERENCES `TB_COMMON_CODE` (`GROUP_CODE`, `CODE_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='교대 계획';

-- 36. TB_SHIFT_ASSIGNMENT (교대조 배정)
CREATE TABLE `TB_SHIFT_ASSIGNMENT` (
    `ASSIGNMENT_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '배정 ID',
    `PLAN_ID` BIGINT NOT NULL COMMENT '교대 계획 ID',
    `USER_ID` VARCHAR(50) NOT NULL COMMENT '사용자 ID',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ASSIGNMENT_ID`),
    UNIQUE KEY `UK_PLAN_USER` (`PLAN_ID`, `USER_ID`),
    FOREIGN KEY (`PLAN_ID`) REFERENCES `TB_SHIFT_PLAN` (`PLAN_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='교대조 배정';

-- 37. TB_SPC_DATA (SPC 데이터)
CREATE TABLE `TB_SPC_DATA` (
    `DATA_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '데이터 ID',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `MEASUREMENT_VALUE` DECIMAL(18,4) NOT NULL COMMENT '측정 값',
    `MEASUREMENT_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '측정 일시',
    `CONTROL_CHART_TYPE` VARCHAR(50) NOT NULL COMMENT '관리도 유형 (X-bar, R, P 등)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`DATA_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`),
    CONSTRAINT `FK_SPC_CHART_TYPE_COMMON_CODE` FOREIGN KEY (`CONTROL_CHART_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 관리도 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SPC 데이터';

-- 38. TB_ALARM_LOG (알람 로그)
CREATE TABLE `TB_ALARM_LOG` (
    `ALARM_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '알람 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `ALARM_GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '알람 공통 코드 그룹',
    `ALARM_CODE` VARCHAR(50) NOT NULL COMMENT '알람 코드',
    `ALARM_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '알람 발생 일시',
    `ALARM_STATUS` VARCHAR(50) NOT NULL COMMENT '알람 상태 (발생, 확인, 해제)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ALARM_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`),
    CONSTRAINT `FK_ALARM_COMMON_CODE` FOREIGN KEY (`ALARM_GROUP_CODE`, `ALARM_CODE`) REFERENCES `TB_COMMON_CODE` (`GROUP_CODE`, `CODE_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='알람 로그';

-- 39. TB_MESSAGE_LOG (메시지 로그)
CREATE TABLE `TB_MESSAGE_LOG` (
    `MESSAGE_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '메시지 ID',
    `SENDER_ID` VARCHAR(50) NOT NULL COMMENT '보낸 사람 ID',
    `RECEIVER_ID` VARCHAR(50) NOT NULL COMMENT '받는 사람 ID',
    `MESSAGE_CONTENT` TEXT NOT NULL COMMENT '메시지 내용',
    `SEND_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '전송 일시',
    `READ_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '읽음 여부',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`MESSAGE_ID`),
    FOREIGN KEY (`SENDER_ID`) REFERENCES `TB_USER` (`USER_ID`),
    FOREIGN KEY (`RECEIVER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='메시지 로그';

-- 40. TB_DOCUMENT_MANAGEMENT (문서 관리)
CREATE TABLE `TB_DOCUMENT_MANAGEMENT` (
    `DOCUMENT_ID` VARCHAR(50) NOT NULL COMMENT '문서 ID',
    `DOCUMENT_TYPE` VARCHAR(50) NOT NULL COMMENT '문서 유형 (예: SOP, 사양서, 작업 표준서)',
    `DOCUMENT_NAME` VARCHAR(255) NOT NULL COMMENT '문서명',
    `VERSION` VARCHAR(20) NOT NULL COMMENT '버전',
    `FILE_PATH` VARCHAR(500) NOT NULL COMMENT '파일 경로',
    `EFFECTIVE_DATE` DATE NOT NULL COMMENT '적용 일자',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`DOCUMENT_ID`),
    UNIQUE KEY `UK_DOC_TYPE_NAME_VERSION` (`DOCUMENT_TYPE`, `DOCUMENT_NAME`, `VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='문서 관리';

-- 41. TB_PARAMETER_MANAGEMENT (설비 파라미터)
CREATE TABLE `TB_PARAMETER_MANAGEMENT` (
    `PARAMETER_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '파라미터 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `PARAMETER_NAME` VARCHAR(100) NOT NULL COMMENT '파라미터명',
    `STANDARD_VALUE` VARCHAR(255) NULL COMMENT '표준 값',
    `UPPER_LIMIT` VARCHAR(255) NULL COMMENT '상한선',
    `LOWER_LIMIT` VARCHAR(255) NULL COMMENT '하한선',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`PARAMETER_ID`),
    UNIQUE KEY `UK_EQUIP_PARAM_NAME` (`EQUIP_ID`, `PARAMETER_NAME`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='설비 파라미터';

-- 42. TB_RAW_DATA_LOG (원시 데이터 로그)
CREATE TABLE `TB_RAW_DATA_LOG` (
    `LOG_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '로그 ID',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `DATA_JSON` JSON NOT NULL COMMENT '수집된 원시 데이터 (JSON 형식)',
    `COLLECTION_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집 일시',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`LOG_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='원시 데이터 로그';

-- 43. TB_REPORT_MANAGEMENT (리포트 관리)
CREATE TABLE `TB_REPORT_MANAGEMENT` (
    `REPORT_ID` VARCHAR(50) NOT NULL COMMENT '리포트 ID',
    `REPORT_NAME` VARCHAR(100) NOT NULL COMMENT '리포트명',
    `REPORT_TYPE` VARCHAR(50) NOT NULL COMMENT '리포트 유형 (일간, 주간, 월간)',
    `GENERATION_CRITERIA` JSON NULL COMMENT '생성 기준 (JSON 형식)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`REPORT_ID`),
    CONSTRAINT `FK_REPORT_TYPE_COMMON_CODE` FOREIGN KEY (`REPORT_TYPE`) REFERENCES `TB_COMMON_CODE` (`CODE_VALUE`) -- 공통 코드의 리포트 유형 참조
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='리포트 관리';

-- 44. TB_USER_LOGIN_LOG (사용자 로그인 로그)
CREATE TABLE `TB_USER_LOGIN_LOG` (
    `LOG_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '로그 ID',
    `USER_ID` VARCHAR(50) NOT NULL COMMENT '사용자 ID',
    `LOGIN_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '로그인 일시',
    `LOGOUT_TIME` DATETIME NULL COMMENT '로그아웃 일시',
    `IP_ADDRESS` VARCHAR(50) NULL COMMENT 'IP 주소',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`LOG_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 로그인 로그';

-- 45. TB_SYSTEM_AUDIT_LOG (시스템 감사 로그)
CREATE TABLE `TB_SYSTEM_AUDIT_LOG` (
    `LOG_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '로그 ID',
    `USER_ID` VARCHAR(50) NULL COMMENT '작업자 ID',
    `ACTION_TYPE` VARCHAR(50) NOT NULL COMMENT '행동 유형 (예: 생성, 수정, 삭제)',
    `TARGET_TABLE` VARCHAR(100) NOT NULL COMMENT '대상 테이블',
    `TARGET_ID` VARCHAR(50) NULL COMMENT '대상 ID',
    `ACTION_DETAILS` TEXT NULL COMMENT '행동 상세',
    `ACTION_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '행동 일시',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`LOG_ID`),
    CONSTRAINT `FK_AUDIT_USER` FOREIGN KEY (`USER_ID`) REFERENCES `TB_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='시스템 감사 로그';

-- 46. TB_ANALYSIS_YIELD (수율 분석)
CREATE TABLE `TB_ANALYSIS_YIELD` (
    `ANALYSIS_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '분석 ID',
    `ANALYSIS_DATE` DATE NOT NULL COMMENT '분석 일자',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `TOTAL_PRODUCTION` DECIMAL(10,2) NOT NULL COMMENT '총 생산량',
    `GOOD_QUANTITY` DECIMAL(10,2) NOT NULL COMMENT '양품 수량',
    `DEFECT_QUANTITY` DECIMAL(10,2) NOT NULL COMMENT '불량 수량',
    `YIELD_RATE` DECIMAL(5,2) NOT NULL COMMENT '수율 (%)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ANALYSIS_ID`),
    UNIQUE KEY `UK_ANALYSIS_DATE_ITEM` (`ANALYSIS_DATE`, `ITEM_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='수율 분석';

-- 47. TB_ANALYSIS_DEFECT (불량률 분석)
CREATE TABLE `TB_ANALYSIS_DEFECT` (
    `ANALYSIS_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '분석 ID',
    `ANALYSIS_DATE` DATE NOT NULL COMMENT '분석 일자',
    `ITEM_ID` VARCHAR(50) NOT NULL COMMENT '품목 ID',
    `DEFECT_GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '불량 공통 코드 그룹',
    `DEFECT_CODE` VARCHAR(50) NOT NULL COMMENT '불량 코드',
    `DEFECT_QUANTITY` DECIMAL(10,2) NOT NULL COMMENT '불량 수량',
    `DEFECT_RATE` DECIMAL(5,2) NOT NULL COMMENT '불량률 (%)',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ANALYSIS_ID`),
    UNIQUE KEY `UK_ANALYSIS_DATE_ITEM` (`ANALYSIS_DATE`, `ITEM_ID`),
    FOREIGN KEY (`ITEM_ID`) REFERENCES `TB_ITEM` (`ITEM_ID`),
    CONSTRAINT `FK_ANALYSIS_DEFECT_COMMON_CODE` FOREIGN KEY (`DEFECT_GROUP_CODE`, `DEFECT_CODE`) REFERENCES `TB_COMMON_CODE` (`GROUP_CODE`, `CODE_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='불량률 분석';

-- 48. TB_ANALYSIS_DOWNTIME (비가동 분석)
CREATE TABLE `TB_ANALYSIS_DOWNTIME` (
    `ANALYSIS_ID` BIGINT AUTO_INCREMENT NOT NULL COMMENT '분석 ID',
    `ANALYSIS_DATE` DATE NOT NULL COMMENT '분석 일자',
    `EQUIP_ID` VARCHAR(50) NOT NULL COMMENT '설비 ID',
    `TOTAL_DOWNTIME_HOURS` DECIMAL(10,2) NOT NULL COMMENT '총 비가동 시간 (시간)',
    `DOWNTIME_COUNT` INT NOT NULL COMMENT '비가동 발생 건수',
    `MAIN_DOWNTIME_GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '주요 비가동 사유 공통 코드 그룹',
    `MAIN_DOWNTIME_CODE` VARCHAR(50) NULL COMMENT '주요 비가동 사유 코드',
    `CREATED_BY` VARCHAR(50) NOT NULL COMMENT '생성자',
    `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    `LAST_MODIFIED_BY` VARCHAR(50) NOT NULL COMMENT '최종 수정자',
    `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일시',
    `IS_DELETED` TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부',
    PRIMARY KEY (`ANALYSIS_ID`),
    FOREIGN KEY (`EQUIP_ID`) REFERENCES `TB_EQUIPMENT` (`EQUIP_ID`),
    CONSTRAINT `FK_ANALYSIS_DOWNTIME_COMMON_CODE` FOREIGN KEY (`MAIN_DOWNTIME_GROUP_CODE`, `MAIN_DOWNTIME_CODE`) REFERENCES `TB_COMMON_CODE` (`GROUP_CODE`, `CODE_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='비가동 분석';
